"""Catalogue (catégories, articles) et fournisseurs — Phase 2.1, avec RLS et droits.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-23 23:54:03.111026+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.config import get_settings

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_catalog_categories_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_categories")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_catalog_categories_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_catalog_categories_tenant_id"), "catalog_categories", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_catalog_categories_tenant_name",
        "catalog_categories",
        ["tenant_id", sa.literal_column("lower(name)")],
        unique=True,
    )
    op.create_table(
        "suppliers",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("contact_name", sa.String(length=150), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("email", sa.String(length=150), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_suppliers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_suppliers_tenant_id_id")),
    )
    op.create_index(op.f("ix_suppliers_tenant_id"), "suppliers", ["tenant_id"], unique=False)
    op.create_table(
        "catalog_articles",
        sa.Column("reference", sa.String(length=50), nullable=False),
        sa.Column("designation", sa.String(length=255), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("main_supplier_id", sa.Uuid(), nullable=True),
        sa.Column("purchase_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("sale_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("min_stock", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("max_stock", sa.Numeric(precision=18, scale=3), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("barcode", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_stock IS NULL OR max_stock >= min_stock",
            name=op.f("ck_catalog_articles_max_stock_gte_min"),
        ),
        sa.CheckConstraint("min_stock >= 0", name=op.f("ck_catalog_articles_min_stock_positive")),
        sa.CheckConstraint(
            "purchase_price >= 0", name=op.f("ck_catalog_articles_purchase_price_positive")
        ),
        sa.CheckConstraint("sale_price >= 0", name=op.f("ck_catalog_articles_sale_price_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "category_id"],
            ["catalog_categories.tenant_id", "catalog_categories.id"],
            name=op.f("fk_catalog_articles_tenant_id_category_id_catalog_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "main_supplier_id"],
            ["suppliers.tenant_id", "suppliers.id"],
            name=op.f("fk_catalog_articles_tenant_id_main_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_catalog_articles_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_articles")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_catalog_articles_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_catalog_articles_category_id"), "catalog_articles", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_catalog_articles_main_supplier_id"),
        "catalog_articles",
        ["main_supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_catalog_articles_tenant_id"), "catalog_articles", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_catalog_articles_tenant_barcode_active",
        "catalog_articles",
        ["tenant_id", "barcode"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "uq_catalog_articles_tenant_reference",
        "catalog_articles",
        ["tenant_id", sa.literal_column("lower(reference)")],
        unique=True,
    )
    # ### end Alembic commands ###
    _enable_rls_and_grants()


def downgrade() -> None:
    _revoke()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_catalog_articles_tenant_reference", table_name="catalog_articles")
    op.drop_index(
        "uq_catalog_articles_tenant_barcode_active",
        table_name="catalog_articles",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(op.f("ix_catalog_articles_tenant_id"), table_name="catalog_articles")
    op.drop_index(op.f("ix_catalog_articles_main_supplier_id"), table_name="catalog_articles")
    op.drop_index(op.f("ix_catalog_articles_category_id"), table_name="catalog_articles")
    op.drop_table("catalog_articles")
    op.drop_index(op.f("ix_suppliers_tenant_id"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index("uq_catalog_categories_tenant_name", table_name="catalog_categories")
    op.drop_index(op.f("ix_catalog_categories_tenant_id"), table_name="catalog_categories")
    op.drop_table("catalog_categories")
    # ### end Alembic commands ###


# --- Isolation et droits (voir DATA_MODEL.md, « Ajouter une table tenant-scoped ») ----------

TABLES = ("catalog_categories", "suppliers", "catalog_articles")


def _app_role() -> str:
    return op.get_bind().dialect.identifier_preparer.quote(get_settings().db_app_role)


def _enable_rls_and_grants() -> None:
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = app_current_tenant_id()) "
            "WITH CHECK (tenant_id = app_current_tenant_id())"
        )
    # Jamais de suppression physique (CAT-03, SUP-04, ART-13) : pas de DELETE.
    op.execute(f"GRANT SELECT, INSERT, UPDATE ON {', '.join(TABLES)} TO {_app_role()}")


def _revoke() -> None:
    op.execute(f"REVOKE ALL ON {', '.join(TABLES)} FROM {_app_role()}")
    for table in TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
