"""Postes des sites : activations sous licence (Phase 3.3-B3, ADR-0035).

- ``license_activations`` : installation cliente (``installation_id`` aléatoire, jamais MAC /
  processeur / IP) activée sur un site sous la licence en vigueur de son abonnement. FK
  composites : abonnement du même tenant ET du même site, licence du même tenant. Une
  installation active au plus une fois par entreprise (index unique partiel : idempotence).
- Finalité : déclencheur ``license_activations_final`` — un poste libéré ne change plus ;
  l'identité d'un poste (site, abonnement, licence, installation, activation) est immuable ;
  un poste actif ne change que sa présence (libellé, version, dernière activité) ou passe
  ``RELEASED``.
- RLS ``ENABLE`` + ``FORCE``. Rôle applicatif : ``tenant_isolation``, ``SELECT, INSERT`` et
  ``UPDATE`` des seules colonnes de présence et de libération (jamais de suppression). Rôle de
  la console : lecture, libération d'un poste ``ACTIVE`` seulement.

Revision ID: 0022
Revises: 0021
Create Date: 2026-09-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.config import get_settings

revision: str = "0022"
down_revision: str | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLE = "license_activations"
RELEASE_COLUMNS = (
    "status",
    "released_at",
    "released_by",
    "release_source",
    "release_reason",
    "updated_at",
)
PRESENCE_COLUMNS = ("label", "client_version", "last_seen_at")


def _roles() -> tuple[str, str]:
    settings = get_settings()
    quote = op.get_bind().dialect.identifier_preparer.quote
    return quote(settings.db_app_role), quote(settings.db_platform_role)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "license_activations",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("license_id", sa.Uuid(), nullable=False),
        sa.Column("installation_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("client_version", sa.String(length=50), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_by", sa.Uuid(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "RELEASED",
                name="activation_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_by", sa.Uuid(), nullable=True),
        sa.Column(
            "release_source",
            sa.Enum(
                "TENANT",
                "TECHNOVA",
                name="activation_release_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("release_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'RELEASED') = (released_at IS NOT NULL AND release_reason IS NOT NULL "
            "AND release_source IS NOT NULL)",
            name=op.f("ck_license_activations_release_consistent"),
        ),
        sa.CheckConstraint(
            "length(btrim(label)) > 0", name=op.f("ck_license_activations_label_present")
        ),
        sa.CheckConstraint(
            "release_reason IS NULL OR length(btrim(release_reason)) > 0",
            name=op.f("ck_license_activations_release_reason_present"),
        ),
        sa.ForeignKeyConstraint(
            ["activated_by"],
            ["users.id"],
            name=op.f("fk_license_activations_activated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["released_by"],
            ["users.id"],
            name=op.f("fk_license_activations_released_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "license_id"],
            ["licenses.tenant_id", "licenses.id"],
            name=op.f("fk_license_activations_tenant_id_license_id_licenses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "subscription_id"],
            ["subscriptions.tenant_id", "subscriptions.site_id", "subscriptions.id"],
            name=op.f("fk_license_activations_tenant_id_site_id_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_license_activations_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_license_activations")),
    )
    op.create_index(
        "ix_license_activations_subscription_status",
        "license_activations",
        ["tenant_id", "subscription_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_license_activations_tenant_id"), "license_activations", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_license_activations_active_installation",
        "license_activations",
        ["tenant_id", "installation_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE FUNCTION license_activations_final() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.status <> 'ACTIVE'
               OR NEW.tenant_id <> OLD.tenant_id
               OR NEW.site_id <> OLD.site_id
               OR NEW.subscription_id <> OLD.subscription_id
               OR NEW.license_id <> OLD.license_id
               OR NEW.installation_id <> OLD.installation_id
               OR NEW.activated_at <> OLD.activated_at
               OR NEW.activated_by IS DISTINCT FROM OLD.activated_by
               OR NEW.created_at <> OLD.created_at
            THEN
                RAISE EXCEPTION 'license activation % is final or immutable', OLD.id
                    USING ERRCODE = 'check_violation';
            END IF;
            RETURN NEW;
        END
        $$
        """
    )
    op.execute(
        f"CREATE TRIGGER license_activations_final BEFORE UPDATE ON {TABLE} "
        "FOR EACH ROW EXECUTE FUNCTION license_activations_final()"
    )

    app_role, platform_role = _roles()
    op.execute(f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {TABLE} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON {TABLE} TO {app_role} "
        "USING (tenant_id = app_current_tenant_id()) "
        "WITH CHECK (tenant_id = app_current_tenant_id())"
    )
    op.execute(f"GRANT SELECT, INSERT ON {TABLE} TO {app_role}")
    op.execute(
        f"GRANT UPDATE ({', '.join(PRESENCE_COLUMNS + RELEASE_COLUMNS)}) ON {TABLE} TO {app_role}"
    )

    op.execute(f"CREATE POLICY platform_read ON {TABLE} FOR SELECT TO {platform_role} USING (true)")
    op.execute(
        f"CREATE POLICY platform_release ON {TABLE} FOR UPDATE TO {platform_role} "
        "USING (status = 'ACTIVE') WITH CHECK (status = 'RELEASED')"
    )
    op.execute(f"GRANT SELECT ON {TABLE} TO {platform_role}")
    op.execute(f"GRANT UPDATE ({', '.join(RELEASE_COLUMNS)}) ON {TABLE} TO {platform_role}")


def downgrade() -> None:
    app_role, platform_role = _roles()
    op.execute(f"REVOKE ALL ON {TABLE} FROM {app_role}")
    op.execute(f"REVOKE ALL ON {TABLE} FROM {platform_role}")
    for policy in ("platform_release", "platform_read", "tenant_isolation"):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {TABLE}")
    op.execute(f"DROP TRIGGER IF EXISTS license_activations_final ON {TABLE}")
    op.execute("DROP FUNCTION IF EXISTS license_activations_final()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_license_activations_active_installation",
        table_name="license_activations",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(op.f("ix_license_activations_tenant_id"), table_name="license_activations")
    op.drop_index("ix_license_activations_subscription_status", table_name="license_activations")
    op.drop_table("license_activations")
    # ### end Alembic commands ###
