"""Console d'administration TechNova (Phase 3.2-F, ADR-0031).

- ``users.is_platform_admin`` : administrateur TechNova, attribué uniquement par la CLI (rôle
  propriétaire). Le rôle applicatif des tenants perd ses droits INSERT/UPDATE sur toute la table
  au profit de droits par colonne **sans** cette colonne, et la RLS (``ENABLE``, sans ``FORCE`` :
  la CLI et les migrations restent sous le rôle propriétaire) lui rend les comptes TechNova
  **invisibles** : ni connexion à l'application des tenants, ni ajout comme membre.
- ``platform_sessions`` : sessions de la console (jeton opaque haché).
- ``platform_audit_logs`` : journal de la plateforme, append-only (droits SELECT/INSERT et
  déclencheur ``platform_audit_logs_append_only`` qui refuse UPDATE et DELETE).
- Rôle SQL de la console (``SM_DB_PLATFORM_ROLE``, défaut ``stockmanager_platform``), sans
  BYPASSRLS, créé par l'exploitation (``docker/postgres/init/02-platform-role.sh``, CI) :
  lecture du catalogue ; mise à jour des **seules colonnes commerciales** de ``plans`` ; lecture
  et verrouillage des seuls comptes TechNova ; sessions et journal de la plateforme. **Aucun
  droit** sur ``tenants``, ``subscriptions`` ni aucune table métier des tenants.

Revision ID: 0017
Revises: 0016
Create Date: 2026-09-25
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.config import get_settings

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Colonnes de ``users`` modifiables par le rôle applicatif (toutes sauf is_platform_admin).
USER_COLUMNS = (
    "id",
    "email",
    "full_name",
    "password_hash",
    "is_active",
    "must_change_password",
    "password_changed_at",
    "failed_login_count",
    "locked_until",
    "last_login_at",
    "locale",
    "created_at",
    "updated_at",
)
# Paramètres commerciaux des plans : seules colonnes modifiables par la console. La structure
# (modules, fonctionnalités, limites, délai de grâce, nom, activation) reste celle du catalogue.
PLAN_COMMERCIAL_COLUMNS = (
    "listed",
    "price_display_enabled",
    "monthly_price",
    "monthly_price_enabled",
    "annual_price",
    "annual_price_enabled",
    "currency",
    "contact_required",
    "commercial_description",
    "display_order",
    "trial_days",
    "updated_at",
)
# Catalogue technique : lecture seule pour la console.
CATALOG_TABLES = (
    "plans",
    "plan_modules",
    "subscription_access_policies",
    "business_sectors",
    "business_profiles",
    "business_profile_modules",
    "ux_profiles",
    "geo_countries",
)


def _quote(role: str) -> str:
    return op.get_bind().dialect.identifier_preparer.quote(role)


def _roles() -> tuple[str, str]:
    settings = get_settings()
    return _quote(settings.db_app_role), _quote(settings.db_platform_role)


def _require_platform_role() -> None:
    role = get_settings().db_platform_role
    exists = op.get_bind().execute(
        sa.text("SELECT 1 FROM pg_roles WHERE rolname = :r AND NOT rolbypassrls"), {"r": role}
    )
    if exists.first() is None:
        raise RuntimeError(
            f"Rôle SQL « {role} » absent (ou BYPASSRLS) : le créer avec "
            "docker/postgres/init/02-platform-role.sh avant la migration."
        )


def upgrade() -> None:
    _require_platform_role()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_platform_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_sessions")),
    )
    op.create_index(
        op.f("ix_platform_sessions_user_id"), "platform_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "platform_audit_logs",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_label", sa.String(length=254), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_platform_audit_logs_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_platform_audit_logs_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_audit_logs")),
    )
    op.create_index(
        op.f("ix_platform_audit_logs_action"), "platform_audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_platform_audit_logs_actor_user_id"),
        "platform_audit_logs",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_audit_logs_occurred", "platform_audit_logs", ["occurred_at"], unique=False
    )
    op.create_index(
        "ix_platform_audit_logs_target",
        "platform_audit_logs",
        ["target_type", "target_id"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column("is_platform_admin", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###

    app_role, platform_role = _roles()
    columns = ", ".join(USER_COLUMNS)

    # --- Comptes TechNova : jamais attribuables ni visibles par le rôle applicatif ---------
    op.execute(f"REVOKE INSERT, UPDATE ON users FROM {app_role}")
    op.execute(f"GRANT INSERT ({columns}), UPDATE ({columns}) ON users TO {app_role}")
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_app_users ON users TO {app_role} "
        "USING (NOT is_platform_admin) WITH CHECK (NOT is_platform_admin)"
    )
    op.execute(
        f"CREATE POLICY platform_admins_read ON users FOR SELECT TO {platform_role} "
        "USING (is_platform_admin)"
    )
    op.execute(
        f"CREATE POLICY platform_admins_lockout ON users FOR UPDATE TO {platform_role} "
        "USING (is_platform_admin) WITH CHECK (is_platform_admin)"
    )

    # --- Journal de la plateforme : append-only --------------------------------------------
    op.execute(
        """
        CREATE FUNCTION platform_audit_logs_append_only() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'platform audit log is append-only'
                USING ERRCODE = 'insufficient_privilege';
        END
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER platform_audit_logs_append_only BEFORE UPDATE OR DELETE "
        "ON platform_audit_logs FOR EACH ROW EXECUTE FUNCTION platform_audit_logs_append_only()"
    )

    # --- Droits minimaux du rôle de la console ----------------------------------------------
    op.execute(f"GRANT USAGE ON SCHEMA public TO {platform_role}")
    op.execute(f"GRANT SELECT ON {', '.join(CATALOG_TABLES)} TO {platform_role}")
    op.execute(f"GRANT UPDATE ({', '.join(PLAN_COMMERCIAL_COLUMNS)}) ON plans TO {platform_role}")
    op.execute(f"GRANT SELECT ON users TO {platform_role}")
    op.execute(
        "GRANT UPDATE (failed_login_count, locked_until, last_login_at, updated_at) "
        f"ON users TO {platform_role}"
    )
    op.execute(f"GRANT SELECT, INSERT, UPDATE ON platform_sessions TO {platform_role}")
    op.execute(f"GRANT SELECT, INSERT ON platform_audit_logs TO {platform_role}")


def downgrade() -> None:
    app_role, platform_role = _roles()
    op.execute(f"REVOKE ALL ON platform_sessions, platform_audit_logs FROM {platform_role}")
    op.execute(f"REVOKE ALL ON users, {', '.join(CATALOG_TABLES)} FROM {platform_role}")
    op.execute(f"REVOKE USAGE ON SCHEMA public FROM {platform_role}")
    op.execute("DROP TRIGGER IF EXISTS platform_audit_logs_append_only ON platform_audit_logs")
    op.execute("DROP FUNCTION IF EXISTS platform_audit_logs_append_only()")
    op.execute("DROP POLICY IF EXISTS platform_admins_lockout ON users")
    op.execute("DROP POLICY IF EXISTS platform_admins_read ON users")
    op.execute("DROP POLICY IF EXISTS tenant_app_users ON users")
    op.execute("ALTER TABLE users DISABLE ROW LEVEL SECURITY")
    op.execute(f"REVOKE INSERT, UPDATE ON users FROM {app_role}")
    op.execute(f"GRANT INSERT, UPDATE ON users TO {app_role}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_platform_admin")
    op.drop_index("ix_platform_audit_logs_target", table_name="platform_audit_logs")
    op.drop_index("ix_platform_audit_logs_occurred", table_name="platform_audit_logs")
    op.drop_index(op.f("ix_platform_audit_logs_actor_user_id"), table_name="platform_audit_logs")
    op.drop_index(op.f("ix_platform_audit_logs_action"), table_name="platform_audit_logs")
    op.drop_table("platform_audit_logs")
    op.drop_index(op.f("ix_platform_sessions_user_id"), table_name="platform_sessions")
    op.drop_table("platform_sessions")
    # ### end Alembic commands ###
