"""Module Ventes (Phase 2.4) : ventes comptant et lignes, isolées par RLS.

- ``sales`` / ``sale_lines`` : FK composites (tenant_id, …) vers site, client, article et
  vente — aucune référence croisée entre tenants possible en base ;
- droits du rôle applicatif : ventes ``SELECT, INSERT, UPDATE`` (jamais supprimées) ; lignes
  ``SELECT, INSERT, UPDATE, DELETE`` (remplacement des lignes d'un brouillon uniquement) ;
- ``stock_movements.source_number`` : numéro lisible du document source (journal générique),
  nul pour les mouvements antérieurs (jamais réécrits).

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-24 10:55:22.022044+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.config import get_settings

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TABLES = ("sales", "sale_lines")
GRANTS = {
    "SELECT, INSERT, UPDATE": ("sales",),
    "SELECT, INSERT, UPDATE, DELETE": ("sale_lines",),
}


def _app_role() -> str:
    return op.get_bind().dialect.identifier_preparer.quote(get_settings().db_app_role)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales",
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "VALIDATED",
                "CANCELLED",
                name="sale_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("sale_date", sa.Date(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validated_by", sa.Uuid(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by", sa.Uuid(), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'CANCELLED' OR (cancelled_at IS NOT NULL "
            "AND cancellation_reason IS NOT NULL)",
            name=op.f("ck_sales_cancelled_has_reason"),
        ),
        sa.CheckConstraint(
            "status <> 'VALIDATED' OR validated_at IS NOT NULL",
            name=op.f("ck_sales_validated_has_date"),
        ),
        sa.CheckConstraint(
            "subtotal >= 0 AND total >= 0", name=op.f("ck_sales_amounts_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by"], ["users.id"], name=op.f("fk_sales_cancelled_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_sales_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["customers.tenant_id", "customers.id"],
            name=op.f("fk_sales_tenant_id_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["sites.tenant_id", "sites.id"],
            name=op.f("fk_sales_tenant_id_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sales_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["validated_by"], ["users.id"], name=op.f("fk_sales_validated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_sales_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_sales_tenant_id_number")),
    )
    op.create_index(op.f("ix_sales_customer_id"), "sales", ["customer_id"], unique=False)
    op.create_index(op.f("ix_sales_site_id"), "sales", ["site_id"], unique=False)
    op.create_index("ix_sales_tenant_date", "sales", ["tenant_id", "sale_date"], unique=False)
    op.create_index(op.f("ix_sales_tenant_id"), "sales", ["tenant_id"], unique=False)
    op.create_table(
        "sale_lines",
        sa.Column("sale_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("line_total >= 0", name=op.f("ck_sale_lines_line_total_non_negative")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sale_lines_quantity_positive")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_sale_lines_unit_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "article_id"],
            ["catalog_articles.tenant_id", "catalog_articles.id"],
            name=op.f("fk_sale_lines_tenant_id_article_id_catalog_articles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sale_id"],
            ["sales.tenant_id", "sales.id"],
            name=op.f("fk_sale_lines_tenant_id_sale_id_sales"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sale_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_lines")),
        sa.UniqueConstraint("sale_id", "article_id", name=op.f("uq_sale_lines_sale_id_article_id")),
    )
    op.create_index(op.f("ix_sale_lines_sale_id"), "sale_lines", ["sale_id"], unique=False)
    op.create_index(op.f("ix_sale_lines_tenant_id"), "sale_lines", ["tenant_id"], unique=False)
    op.add_column(
        "stock_movements", sa.Column("source_number", sa.String(length=30), nullable=True)
    )
    # ### end Alembic commands ###

    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = app_current_tenant_id()) "
            "WITH CHECK (tenant_id = app_current_tenant_id())"
        )
    role = _app_role()
    for privileges, tables in GRANTS.items():
        op.execute(f"GRANT {privileges} ON {', '.join(tables)} TO {role}")


def downgrade() -> None:
    op.execute(f"REVOKE ALL ON {', '.join(TABLES)} FROM {_app_role()}")
    for table in TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_movements", "source_number")
    op.drop_index(op.f("ix_sale_lines_tenant_id"), table_name="sale_lines")
    op.drop_index(op.f("ix_sale_lines_sale_id"), table_name="sale_lines")
    op.drop_table("sale_lines")
    op.drop_index(op.f("ix_sales_tenant_id"), table_name="sales")
    op.drop_index("ix_sales_tenant_date", table_name="sales")
    op.drop_index(op.f("ix_sales_site_id"), table_name="sales")
    op.drop_index(op.f("ix_sales_customer_id"), table_name="sales")
    op.drop_table("sales")
    # ### end Alembic commands ###
