"""Paiements d'abonnement (Phase 3.3-A, ADR-0032).

- ``subscriptions`` : unicité ``(tenant_id, id)``, cible de la clé étrangère composite.
- ``subscription_payments`` : paiement de l'abonnement **à TechNova**, déclaré par l'entreprise
  (``PENDING``), confirmé ou rejeté par TechNova (``CONFIRMED`` / ``REJECTED``). Distinct des
  paiements des ventes (``payments``). FK composite ``(tenant_id, subscription_id)`` : jamais un
  paiement lié à l'abonnement d'un autre tenant. Clé d'idempotence unique par tenant.
- Décision **définitive** : contraintes ``CHECK`` et déclencheur
  ``subscription_payments_final`` (une décision prise n'est plus modifiable ; montant, devise,
  période, moyen, référence, clé, déclarant, abonnement et tenant ne changent jamais).
- RLS ``ENABLE`` + ``FORCE`` ; rôle applicatif : ``tenant_isolation``, droits ``SELECT,
  INSERT`` (jamais de modification ni de suppression). Rôle de la console : lecture
  (``platform_read``) et décision seulement (``platform_decide`` : ligne ``PENDING`` →
  ``CONFIRMED`` / ``REJECTED``), mise à jour des seules colonnes de décision ; ni insertion ni
  suppression.

Aucune activation : un paiement confirmé ne modifie ni l'abonnement ni le tenant (3.3-B).

Revision ID: 0019
Revises: 0018
Create Date: 2026-09-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.config import get_settings

revision: str = "0019"
down_revision: str | None = "0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLE = "subscription_payments"
DECISION_COLUMNS = ("status", "decided_by", "decided_at", "rejection_reason", "updated_at")


def _roles() -> tuple[str, str]:
    settings = get_settings()
    quote = op.get_bind().dialect.identifier_preparer.quote
    return quote(settings.db_app_role), quote(settings.db_platform_role)


def upgrade() -> None:
    op.create_unique_constraint(
        op.f("uq_subscriptions_tenant_id_id"), "subscriptions", ["tenant_id", "id"]
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_payments",
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum(
                "BANK_TRANSFER",
                "MOBILE_MONEY",
                "CASH",
                "CHECK",
                "CARD",
                "OTHER",
                name="subscription_payment_method",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("declared_reference", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column("declared_by", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "REJECTED",
                name="subscription_payment_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'PENDING') = (decided_by IS NULL AND decided_at IS NULL)",
            name=op.f("ck_subscription_payments_decision_consistent"),
        ),
        sa.CheckConstraint(
            "(status = 'REJECTED') = (rejection_reason IS NOT NULL)",
            name=op.f("ck_subscription_payments_rejection_has_reason"),
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_subscription_payments_iso_currency")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_subscription_payments_amount_positive")),
        sa.CheckConstraint(
            "length(btrim(declared_reference)) > 0",
            name=op.f("ck_subscription_payments_reference_present"),
        ),
        sa.CheckConstraint(
            "period_end > period_start", name=op.f("ck_subscription_payments_period_ordered")
        ),
        sa.CheckConstraint(
            "rejection_reason IS NULL OR length(btrim(rejection_reason)) > 0",
            name=op.f("ck_subscription_payments_rejection_reason_present"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_subscription_payments_decided_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["declared_by"],
            ["users.id"],
            name=op.f("fk_subscription_payments_declared_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "subscription_id"],
            ["subscriptions.tenant_id", "subscriptions.id"],
            name=op.f("fk_subscription_payments_tenant_id_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_subscription_payments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_payments")),
        sa.UniqueConstraint(
            "tenant_id",
            "idempotency_key",
            name=op.f("uq_subscription_payments_tenant_id_idempotency_key"),
        ),
    )
    op.create_index(
        "ix_subscription_payments_status_created",
        "subscription_payments",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_subscription_payments_tenant_created",
        "subscription_payments",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_payments_tenant_id"),
        "subscription_payments",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE FUNCTION subscription_payments_final() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.status <> 'PENDING'
               OR NEW.tenant_id <> OLD.tenant_id
               OR NEW.subscription_id <> OLD.subscription_id
               OR NEW.amount <> OLD.amount
               OR NEW.currency <> OLD.currency
               OR NEW.period_start <> OLD.period_start
               OR NEW.period_end <> OLD.period_end
               OR NEW.payment_method <> OLD.payment_method
               OR NEW.declared_reference <> OLD.declared_reference
               OR NEW.idempotency_key <> OLD.idempotency_key
               OR NEW.declared_by <> OLD.declared_by
               OR NEW.created_at <> OLD.created_at
            THEN
                RAISE EXCEPTION 'subscription payment % is final or immutable', OLD.id
                    USING ERRCODE = 'check_violation';
            END IF;
            RETURN NEW;
        END
        $$
        """
    )
    op.execute(
        f"CREATE TRIGGER subscription_payments_final BEFORE UPDATE ON {TABLE} "
        "FOR EACH ROW EXECUTE FUNCTION subscription_payments_final()"
    )

    app_role, platform_role = _roles()
    op.execute(f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {TABLE} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON {TABLE} TO {app_role} "
        "USING (tenant_id = app_current_tenant_id()) "
        "WITH CHECK (tenant_id = app_current_tenant_id())"
    )
    op.execute(f"GRANT SELECT, INSERT ON {TABLE} TO {app_role}")

    op.execute(f"CREATE POLICY platform_read ON {TABLE} FOR SELECT TO {platform_role} USING (true)")
    op.execute(
        f"CREATE POLICY platform_decide ON {TABLE} FOR UPDATE TO {platform_role} "
        "USING (status = 'PENDING') WITH CHECK (status IN ('CONFIRMED', 'REJECTED'))"
    )
    op.execute(f"GRANT SELECT ON {TABLE} TO {platform_role}")
    op.execute(f"GRANT UPDATE ({', '.join(DECISION_COLUMNS)}) ON {TABLE} TO {platform_role}")


def downgrade() -> None:
    app_role, platform_role = _roles()
    op.execute(f"REVOKE ALL ON {TABLE} FROM {app_role}")
    op.execute(f"REVOKE ALL ON {TABLE} FROM {platform_role}")
    op.execute(f"DROP POLICY IF EXISTS platform_decide ON {TABLE}")
    op.execute(f"DROP POLICY IF EXISTS platform_read ON {TABLE}")
    op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {TABLE}")
    op.execute(f"DROP TRIGGER IF EXISTS subscription_payments_final ON {TABLE}")
    op.execute("DROP FUNCTION IF EXISTS subscription_payments_final()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_payments_tenant_id"), table_name=TABLE)
    op.drop_index("ix_subscription_payments_tenant_created", table_name=TABLE)
    op.drop_index("ix_subscription_payments_status_created", table_name=TABLE)
    op.drop_table(TABLE)
    op.drop_constraint(op.f("uq_subscriptions_tenant_id_id"), "subscriptions", type_="unique")
    # ### end Alembic commands ###
