"""Renouvellement par site et notifications d'échéance (Phase 3.3-B4, ADR-0036).

- ``plans`` : tarification par poste — ``included_activations`` (postes compris dans le prix
  de base), ``monthly_activation_price`` / ``annual_activation_price`` (poste supplémentaire ;
  nul : sur devis). Paramètres commerciaux modifiables par TechNova (console).
- ``subscriptions`` : tarif par poste **figé** avec le prix de base
  (``included_activations_at_subscription``, ``activation_price_at_subscription``) ; les
  abonnements existants dotés d'un prix figé reçoivent 1 poste compris, sans tarif par poste.
- ``subscription_payments.requested_activations`` : changement **explicite** du nombre de
  postes demandé avec le paiement (nul : reconduction) ; immuable (déclencheur de finalité
  étendu).
- ``notifications`` (tenant, site, abonnement ; unicité ``(abonnement, type, étape,
  échéance)`` ; jamais modifiées ni supprimées) et ``notification_reads`` (lu / non lu par
  membre). RLS ``ENABLE`` + ``FORCE`` ; rôle applicatif : lecture des notifications, lecture et
  ajout de SES lectures ; rôle de la console (job ``stockmanager notifications run``) : lecture
  et insertion des notifications seulement.

Revision ID: 0023
Revises: 0022
Create Date: 2026-09-30
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.config import get_settings

revision: str = "0023"
down_revision: str | None = "0022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PLAN_PRICING_COLUMNS = (
    "included_activations",
    "monthly_activation_price",
    "annual_activation_price",
)
SUBSCRIPTION_TARIFF_COLUMNS = (
    "included_activations_at_subscription",
    "activation_price_at_subscription",
)

PAYMENT_FINAL_TEMPLATE = """
CREATE OR REPLACE FUNCTION subscription_payments_final() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.status <> 'PENDING'
       OR NEW.tenant_id <> OLD.tenant_id
       OR NEW.subscription_id <> OLD.subscription_id
       OR NEW.amount <> OLD.amount
       OR NEW.currency <> OLD.currency
       OR NEW.period_start <> OLD.period_start
       OR NEW.period_end <> OLD.period_end
       OR NEW.payment_method <> OLD.payment_method
       OR NEW.declared_reference <> OLD.declared_reference
       OR NEW.idempotency_key <> OLD.idempotency_key
       OR NEW.declared_by <> OLD.declared_by
       OR NEW.created_at <> OLD.created_at{extra}
    THEN
        RAISE EXCEPTION 'subscription payment % is final or immutable', OLD.id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END
$$
"""


def _roles() -> tuple[str, str]:
    settings = get_settings()
    quote = op.get_bind().dialect.identifier_preparer.quote
    return quote(settings.db_app_role), quote(settings.db_platform_role)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("site_id", sa.Uuid(), nullable=True),
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("reference_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SENT",
                "SKIPPED",
                name="notification_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["sites.tenant_id", "sites.id"],
            name=op.f("fk_notifications_tenant_id_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "subscription_id"],
            ["subscriptions.tenant_id", "subscriptions.id"],
            name=op.f("fk_notifications_tenant_id_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_notifications_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_notifications_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "subscription_id",
            "kind",
            "step",
            "reference_date",
            name=op.f("uq_notifications_tenant_id_subscription_id_kind_step_reference_date"),
        ),
    )
    op.create_index(
        "ix_notifications_tenant_created",
        "notifications",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_tenant_id"), "notifications", ["tenant_id"], unique=False
    )
    op.create_table(
        "notification_reads",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("notification_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "notification_id"],
            ["notifications.tenant_id", "notifications.id"],
            name=op.f("fk_notification_reads_tenant_id_notification_id_notifications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_notification_reads_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_reads_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("notification_id", "user_id", name=op.f("pk_notification_reads")),
    )
    op.create_index(
        op.f("ix_notification_reads_tenant_id"), "notification_reads", ["tenant_id"], unique=False
    )
    op.add_column(
        "plans", sa.Column("included_activations", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "plans",
        sa.Column("monthly_activation_price", sa.Numeric(precision=18, scale=2), nullable=True),
    )
    op.add_column(
        "plans",
        sa.Column("annual_activation_price", sa.Numeric(precision=18, scale=2), nullable=True),
    )
    op.add_column(
        "subscription_payments", sa.Column("requested_activations", sa.Integer(), nullable=True)
    )
    op.add_column(
        "subscriptions",
        sa.Column("included_activations_at_subscription", sa.Integer(), nullable=True),
    )
    op.add_column(
        "subscriptions",
        sa.Column(
            "activation_price_at_subscription", sa.Numeric(precision=18, scale=2), nullable=True
        ),
    )
    # ### end Alembic commands ###

    # Abonnements existants dotés d'un prix figé : 1 poste compris, aucun tarif par poste.
    op.execute(
        "UPDATE subscriptions SET included_activations_at_subscription = 1 "
        "WHERE price_at_subscription IS NOT NULL"
    )
    op.create_check_constraint(
        "included_activations_positive", "plans", "included_activations >= 1"
    )
    op.create_check_constraint(
        "monthly_activation_price_positive",
        "plans",
        "monthly_activation_price IS NULL OR monthly_activation_price >= 0",
    )
    op.create_check_constraint(
        "annual_activation_price_positive",
        "plans",
        "annual_activation_price IS NULL OR annual_activation_price >= 0",
    )
    op.create_check_constraint(
        "included_activations_snapshot_complete",
        "subscriptions",
        "(included_activations_at_subscription IS NULL) = (price_at_subscription IS NULL)",
    )
    op.create_check_constraint(
        "activation_price_snapshot_complete",
        "subscriptions",
        "activation_price_at_subscription IS NULL OR price_at_subscription IS NOT NULL",
    )
    op.create_check_constraint(
        "requested_activations_range",
        "subscription_payments",
        "requested_activations IS NULL OR requested_activations BETWEEN 1 AND 10000",
    )
    op.execute(
        PAYMENT_FINAL_TEMPLATE.format(
            extra="\n       OR NEW.requested_activations IS DISTINCT FROM OLD.requested_activations"
        )
    )

    app_role, platform_role = _roles()
    for table in ("notifications", "notification_reads"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    # Notifications : lues par l'entreprise, écrites par le job de la plateforme seulement.
    op.execute(
        f"CREATE POLICY tenant_isolation ON notifications FOR SELECT TO {app_role} "
        "USING (tenant_id = app_current_tenant_id())"
    )
    op.execute(f"GRANT SELECT ON notifications TO {app_role}")
    op.execute(
        f"CREATE POLICY platform_read ON notifications FOR SELECT TO {platform_role} USING (true)"
    )
    op.execute(
        f"CREATE POLICY platform_notify ON notifications FOR INSERT TO {platform_role} "
        "WITH CHECK (true)"
    )
    op.execute(f"GRANT SELECT, INSERT ON notifications TO {platform_role}")
    # Lectures : chaque membre n'enregistre que les siennes.
    op.execute(
        f"CREATE POLICY tenant_isolation ON notification_reads FOR SELECT TO {app_role} "
        "USING (tenant_id = app_current_tenant_id())"
    )
    op.execute(
        f"CREATE POLICY own_reads ON notification_reads FOR INSERT TO {app_role} "
        "WITH CHECK (tenant_id = app_current_tenant_id() AND user_id = app_current_user_id())"
    )
    op.execute(f"GRANT SELECT, INSERT ON notification_reads TO {app_role}")
    # Console : tarification par poste (paramètres commerciaux) et tarif figé au changement de
    # plan.
    op.execute(f"GRANT UPDATE ({', '.join(PLAN_PRICING_COLUMNS)}) ON plans TO {platform_role}")
    op.execute(
        f"GRANT UPDATE ({', '.join(SUBSCRIPTION_TARIFF_COLUMNS)}) ON subscriptions "
        f"TO {platform_role}"
    )


def downgrade() -> None:
    app_role, platform_role = _roles()
    op.execute(
        f"REVOKE UPDATE ({', '.join(SUBSCRIPTION_TARIFF_COLUMNS)}) ON subscriptions "
        f"FROM {platform_role}"
    )
    op.execute(f"REVOKE UPDATE ({', '.join(PLAN_PRICING_COLUMNS)}) ON plans FROM {platform_role}")
    for table in ("notification_reads", "notifications"):
        op.execute(f"REVOKE ALL ON {table} FROM {app_role}")
        op.execute(f"REVOKE ALL ON {table} FROM {platform_role}")
    for policy, table in (
        ("own_reads", "notification_reads"),
        ("tenant_isolation", "notification_reads"),
        ("platform_notify", "notifications"),
        ("platform_read", "notifications"),
        ("tenant_isolation", "notifications"),
    ):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {table}")
    op.execute(PAYMENT_FINAL_TEMPLATE.format(extra=""))
    for name, table in (
        ("requested_activations_range", "subscription_payments"),
        ("activation_price_snapshot_complete", "subscriptions"),
        ("included_activations_snapshot_complete", "subscriptions"),
        ("annual_activation_price_positive", "plans"),
        ("monthly_activation_price_positive", "plans"),
        ("included_activations_positive", "plans"),
    ):
        op.drop_constraint(op.f(f"ck_{table}_{name}"), table, type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "activation_price_at_subscription")
    op.drop_column("subscriptions", "included_activations_at_subscription")
    op.drop_column("subscription_payments", "requested_activations")
    op.drop_column("plans", "annual_activation_price")
    op.drop_column("plans", "monthly_activation_price")
    op.drop_column("plans", "included_activations")
    op.drop_index(op.f("ix_notification_reads_tenant_id"), table_name="notification_reads")
    op.drop_table("notification_reads")
    op.drop_index(op.f("ix_notifications_tenant_id"), table_name="notifications")
    op.drop_index("ix_notifications_tenant_created", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
