"""Transferts inter-sites (Phase 2.5, fonctionnalité de plan ``stock.transfers``).

- ``stock_transfers`` / ``stock_transfer_lines`` : FK composites (tenant_id, …) vers les deux
  sites, l'article et le transfert — aucune référence croisée entre tenants possible en base ;
  ``CHECK source_site_id <> destination_site_id`` ;
- droits du rôle applicatif : transferts ``SELECT, INSERT, UPDATE`` (jamais supprimés) ; lignes
  ``SELECT, INSERT, UPDATE, DELETE`` (remplacement des lignes d'un brouillon uniquement) ;
- ``stock_movements`` : la garde anti double application devient unique par
  (ligne source, type, **site**) — l'annulation d'un transfert inverse un mouvement sur chacun
  des deux sites. Toujours un seul mouvement d'un type donné par ligne et par site.

Retour arrière refusé si des transferts existent : leurs mouvements (append-only) resteraient
dans le journal sans document et l'ancienne contrainte ne pourrait pas être rétablie.

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-24 15:06:30.853355+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.config import get_settings

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TABLES = ("stock_transfers", "stock_transfer_lines")
GRANTS = {
    "SELECT, INSERT, UPDATE": ("stock_transfers",),
    "SELECT, INSERT, UPDATE, DELETE": ("stock_transfer_lines",),
}


def _app_role() -> str:
    return op.get_bind().dialect.identifier_preparer.quote(get_settings().db_app_role)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_transfers",
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("source_site_id", sa.Uuid(), nullable=False),
        sa.Column("destination_site_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "VALIDATED",
                "CANCELLED",
                name="document_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("operation_date", sa.Date(), nullable=False),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validated_by", sa.Uuid(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by", sa.Uuid(), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'CANCELLED' OR (cancelled_at IS NOT NULL "
            "AND cancellation_reason IS NOT NULL)",
            name=op.f("ck_stock_transfers_cancelled_has_reason"),
        ),
        sa.CheckConstraint(
            "status <> 'VALIDATED' OR validated_at IS NOT NULL",
            name=op.f("ck_stock_transfers_validated_has_date"),
        ),
        sa.CheckConstraint(
            "source_site_id <> destination_site_id", name=op.f("ck_stock_transfers_distinct_sites")
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by"], ["users.id"], name=op.f("fk_stock_transfers_cancelled_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_stock_transfers_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "destination_site_id"],
            ["sites.tenant_id", "sites.id"],
            name=op.f("fk_stock_transfers_tenant_id_destination_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_site_id"],
            ["sites.tenant_id", "sites.id"],
            name=op.f("fk_stock_transfers_tenant_id_source_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stock_transfers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["validated_by"], ["users.id"], name=op.f("fk_stock_transfers_validated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfers")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_stock_transfers_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "number", name=op.f("uq_stock_transfers_tenant_id_number")
        ),
    )
    op.create_index(
        op.f("ix_stock_transfers_destination_site_id"),
        "stock_transfers",
        ["destination_site_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfers_source_site_id"),
        "stock_transfers",
        ["source_site_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_transfers_tenant_date",
        "stock_transfers",
        ["tenant_id", "operation_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfers_tenant_id"), "stock_transfers", ["tenant_id"], unique=False
    )
    op.create_table(
        "stock_transfer_lines",
        sa.Column("transfer_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_transfer_lines_quantity_positive")),
        sa.CheckConstraint(
            "unit_cost IS NULL OR unit_cost >= 0",
            name=op.f("ck_stock_transfer_lines_unit_cost_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "article_id"],
            ["catalog_articles.tenant_id", "catalog_articles.id"],
            name=op.f("fk_stock_transfer_lines_tenant_id_article_id_catalog_articles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "transfer_id"],
            ["stock_transfers.tenant_id", "stock_transfers.id"],
            name=op.f("fk_stock_transfer_lines_tenant_id_transfer_id_stock_transfers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stock_transfer_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfer_lines")),
        sa.UniqueConstraint(
            "transfer_id", "article_id", name=op.f("uq_stock_transfer_lines_transfer_id_article_id")
        ),
    )
    op.create_index(
        op.f("ix_stock_transfer_lines_tenant_id"),
        "stock_transfer_lines",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfer_lines_transfer_id"),
        "stock_transfer_lines",
        ["transfer_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("uq_stock_movements_tenant_id_source_line_id_movement_type"),
        "stock_movements",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_stock_movements_line_type_site",
        "stock_movements",
        ["tenant_id", "source_line_id", "movement_type", "site_id"],
    )
    # ### end Alembic commands ###

    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = app_current_tenant_id()) "
            "WITH CHECK (tenant_id = app_current_tenant_id())"
        )
    role = _app_role()
    for privileges, tables in GRANTS.items():
        op.execute(f"GRANT {privileges} ON {', '.join(tables)} TO {role}")


def downgrade() -> None:
    # Propriétaire de la table : la politique RLS ne s'applique pas à cette vérification
    # (FORCE désactivé le temps de la lecture).
    op.execute("ALTER TABLE stock_transfers NO FORCE ROW LEVEL SECURITY")
    existing = op.get_bind().execute(sa.text("SELECT count(*) FROM stock_transfers")).scalar()
    if existing:
        raise RuntimeError(
            f"Retour arrière impossible : {existing} transfert(s) enregistré(s) "
            "(mouvements de stock append-only)."
        )
    op.execute(f"REVOKE ALL ON {', '.join(TABLES)} FROM {_app_role()}")
    for table in TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_stock_movements_line_type_site", "stock_movements", type_="unique")
    op.create_unique_constraint(
        op.f("uq_stock_movements_tenant_id_source_line_id_movement_type"),
        "stock_movements",
        ["tenant_id", "source_line_id", "movement_type"],
    )
    op.drop_index(op.f("ix_stock_transfer_lines_transfer_id"), table_name="stock_transfer_lines")
    op.drop_index(op.f("ix_stock_transfer_lines_tenant_id"), table_name="stock_transfer_lines")
    op.drop_table("stock_transfer_lines")
    op.drop_index(op.f("ix_stock_transfers_tenant_id"), table_name="stock_transfers")
    op.drop_index("ix_stock_transfers_tenant_date", table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_source_site_id"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_destination_site_id"), table_name="stock_transfers")
    op.drop_table("stock_transfers")
    # ### end Alembic commands ###
