"""Caisse (Phase 2.9, ADR-0022).

- ``cash_registers`` : caisses d'un site (code ``CAI-001`` unique par tenant), jamais
  supprimées (désactivation) ;
- ``cash_sessions`` : sessions d'une caisse (``SES-000001``) ; une seule session ``OPEN`` par
  caisse (index unique partiel) ; fond initial ≥ 0 ; clôture : solde théorique, compté et
  écart obligatoires, écart = compté − théorique (``CHECK``) ;
- ``cash_movements`` : mouvements append-only (montant > 0, le type fixe le sens) ; FK
  composites vers la session (même tenant, caisse et site) et vers le paiement encaissé (même
  tenant ET même site : nouvelle unicité ``(tenant_id, id, site_id)`` sur ``payments``) ;
- RLS ``ENABLE`` + ``FORCE``, politique ``tenant_isolation`` ; droits du rôle applicatif :
  ``SELECT, INSERT, UPDATE`` (caisses, sessions), ``SELECT, INSERT`` (mouvements : jamais
  modifiés ni supprimés).

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-25
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.config import get_settings

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


GRANTS = {
    "cash_registers": "SELECT, INSERT, UPDATE",
    "cash_sessions": "SELECT, INSERT, UPDATE",
    "cash_movements": "SELECT, INSERT",
}


def _app_role() -> str:
    return op.get_bind().dialect.identifier_preparer.quote(get_settings().db_app_role)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Cible de la FK composite (tenant, paiement, site) des mouvements : AVANT les tables.
    op.create_unique_constraint(
        op.f("uq_payments_tenant_id_id_site_id"), "payments", ["tenant_id", "id", "site_id"]
    )
    op.create_table(
        "cash_registers",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_cash_registers_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["sites.tenant_id", "sites.id"],
            name=op.f("fk_cash_registers_tenant_id_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_cash_registers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_registers")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_cash_registers_tenant_id_code")),
        sa.UniqueConstraint(
            "tenant_id", "id", "site_id", name=op.f("uq_cash_registers_tenant_id_id_site_id")
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_cash_registers_tenant_id_id")),
    )
    op.create_index(op.f("ix_cash_registers_site_id"), "cash_registers", ["site_id"], unique=False)
    op.create_index(
        op.f("ix_cash_registers_tenant_id"), "cash_registers", ["tenant_id"], unique=False
    )
    op.create_table(
        "cash_sessions",
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("cash_register_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLOSED",
                name="cash_session_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("opening_float", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opened_by", sa.Uuid(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_by", sa.Uuid(), nullable=True),
        sa.Column("theoretical_balance", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("counted_balance", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("variance", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("closing_note", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'CLOSED' OR (closed_at IS NOT NULL AND theoretical_balance IS NOT NULL "
            "AND counted_balance IS NOT NULL AND variance IS NOT NULL)",
            name=op.f("ck_cash_sessions_closed_is_counted"),
        ),
        sa.CheckConstraint(
            "counted_balance IS NULL OR counted_balance >= 0",
            name=op.f("ck_cash_sessions_counted_positive"),
        ),
        sa.CheckConstraint(
            "opening_float >= 0", name=op.f("ck_cash_sessions_opening_float_non_negative")
        ),
        sa.CheckConstraint(
            "variance IS NULL OR variance = counted_balance - theoretical_balance",
            name=op.f("ck_cash_sessions_variance_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["closed_by"], ["users.id"], name=op.f("fk_cash_sessions_closed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["opened_by"], ["users.id"], name=op.f("fk_cash_sessions_opened_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "cash_register_id", "site_id"],
            ["cash_registers.tenant_id", "cash_registers.id", "cash_registers.site_id"],
            name=op.f("fk_cash_sessions_tenant_id_cash_register_id_site_id_cash_registers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_cash_sessions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_sessions")),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            "cash_register_id",
            "site_id",
            name=op.f("uq_cash_sessions_tenant_id_id_cash_register_id_site_id"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_cash_sessions_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_cash_sessions_tenant_id_number")),
    )
    op.create_index(
        op.f("ix_cash_sessions_cash_register_id"),
        "cash_sessions",
        ["cash_register_id"],
        unique=False,
    )
    op.create_index(op.f("ix_cash_sessions_site_id"), "cash_sessions", ["site_id"], unique=False)
    op.create_index(
        op.f("ix_cash_sessions_tenant_id"), "cash_sessions", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_cash_sessions_tenant_opened", "cash_sessions", ["tenant_id", "opened_at"], unique=False
    )
    op.create_index(
        "uq_cash_sessions_one_open_per_register",
        "cash_sessions",
        ["tenant_id", "cash_register_id"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.create_table(
        "cash_movements",
        sa.Column("cash_session_id", sa.Uuid(), nullable=False),
        sa.Column("cash_register_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column(
            "movement_type",
            sa.Enum(
                "OPENING_FLOAT",
                "SALE_CASH_IN",
                "SALE_CASH_REVERSAL",
                "MANUAL_CASH_IN",
                "MANUAL_CASH_OUT",
                name="cash_movement_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "CASH_ADDITION",
                "EXPENSE",
                "BANK_DEPOSIT",
                "WITHDRAWAL",
                "CORRECTION",
                "OTHER",
                name="cash_movement_category",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("source_type", sa.String(length=30), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("source_number", sa.String(length=30), nullable=True),
        sa.Column("payment_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "movement_type NOT IN ('MANUAL_CASH_IN', 'MANUAL_CASH_OUT') "
            "OR (reason IS NOT NULL AND category IS NOT NULL)",
            name=op.f("ck_cash_movements_manual_has_reason"),
        ),
        sa.CheckConstraint(
            "movement_type NOT IN ('SALE_CASH_IN', 'SALE_CASH_REVERSAL') OR payment_id IS NOT NULL",
            name=op.f("ck_cash_movements_sale_has_payment"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_cash_movements_amount_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_cash_movements_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "cash_session_id", "cash_register_id", "site_id"],
            [
                "cash_sessions.tenant_id",
                "cash_sessions.id",
                "cash_sessions.cash_register_id",
                "cash_sessions.site_id",
            ],
            name=op.f(
                "fk_cash_movements_tenant_id_cash_session_id_cash_register_id_site_id_cash_sessions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "payment_id", "site_id"],
            ["payments.tenant_id", "payments.id", "payments.site_id"],
            name=op.f("fk_cash_movements_tenant_id_payment_id_site_id_payments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_cash_movements_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_movements")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_cash_movements_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name=op.f("uq_cash_movements_tenant_id_idempotency_key")
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "payment_id",
            "movement_type",
            name=op.f("uq_cash_movements_tenant_id_payment_id_movement_type"),
        ),
    )
    op.create_index(
        op.f("ix_cash_movements_cash_register_id"),
        "cash_movements",
        ["cash_register_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cash_movements_payment_id"), "cash_movements", ["payment_id"], unique=False
    )
    op.create_index(op.f("ix_cash_movements_site_id"), "cash_movements", ["site_id"], unique=False)
    op.create_index(
        op.f("ix_cash_movements_tenant_id"), "cash_movements", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_cash_movements_tenant_occurred",
        "cash_movements",
        ["tenant_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_cash_movements_tenant_session",
        "cash_movements",
        ["tenant_id", "cash_session_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    for table, grants in GRANTS.items():
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = app_current_tenant_id()) "
            "WITH CHECK (tenant_id = app_current_tenant_id())"
        )
        op.execute(f"GRANT {grants} ON {table} TO {_app_role()}")


def downgrade() -> None:
    for table in reversed(GRANTS):
        op.execute(f"REVOKE ALL ON {table} FROM {_app_role()}")
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cash_movements_tenant_session", table_name="cash_movements")
    op.drop_index("ix_cash_movements_tenant_occurred", table_name="cash_movements")
    op.drop_index(op.f("ix_cash_movements_tenant_id"), table_name="cash_movements")
    op.drop_index(op.f("ix_cash_movements_site_id"), table_name="cash_movements")
    op.drop_index(op.f("ix_cash_movements_payment_id"), table_name="cash_movements")
    op.drop_index(op.f("ix_cash_movements_cash_register_id"), table_name="cash_movements")
    op.drop_table("cash_movements")
    op.drop_index(
        "uq_cash_sessions_one_open_per_register",
        table_name="cash_sessions",
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.drop_index("ix_cash_sessions_tenant_opened", table_name="cash_sessions")
    op.drop_index(op.f("ix_cash_sessions_tenant_id"), table_name="cash_sessions")
    op.drop_index(op.f("ix_cash_sessions_site_id"), table_name="cash_sessions")
    op.drop_index(op.f("ix_cash_sessions_cash_register_id"), table_name="cash_sessions")
    op.drop_table("cash_sessions")
    op.drop_index(op.f("ix_cash_registers_tenant_id"), table_name="cash_registers")
    op.drop_index(op.f("ix_cash_registers_site_id"), table_name="cash_registers")
    op.drop_table("cash_registers")
    # Après la table des mouvements (sa FK composite en dépend).
    op.drop_constraint(op.f("uq_payments_tenant_id_id_site_id"), "payments", type_="unique")
    # ### end Alembic commands ###
