"""Inventaires (Phase 2.6, module ``inventory_count``, ADR-0019).

- ``inventories`` / ``inventory_lines`` : FK composites (tenant_id, …) vers le site, l'article
  et l'inventaire — aucune référence croisée entre tenants possible en base ; numéro unique
  par tenant ; un article une seule fois par inventaire ; quantité physique ≥ 0 ; écart figé
  cohérent (``quantity_variance = quantity_physical − stock_theoretical_at_validation``) ;
- RLS ``ENABLE`` + ``FORCE`` et politique ``tenant_isolation`` ;
- droits du rôle applicatif : inventaires ``SELECT, INSERT, UPDATE`` (jamais supprimés) ;
  lignes ``SELECT, INSERT, UPDATE, DELETE`` (articles d'un brouillon uniquement).

Aucun changement de ``stock_movements`` : les ajustements utilisent le type ``ADJUSTMENT``
déjà réservé (``source_type = 'inventory_count'``).

Retour arrière **destructif** (comme ``0007`` et ``0008``) : supprime les inventaires et leurs
mouvements d'ajustement ; les niveaux de stock ne sont pas recalculés. Réservé au
développement.

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-24 19:32:45.109516+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.config import get_settings

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TABLES = ("inventories", "inventory_lines")
GRANTS = {
    "SELECT, INSERT, UPDATE": ("inventories",),
    "SELECT, INSERT, UPDATE, DELETE": ("inventory_lines",),
}


def _app_role() -> str:
    return op.get_bind().dialect.identifier_preparer.quote(get_settings().db_app_role)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventories",
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "COUNTING",
                "READY_TO_VALIDATE",
                "VALIDATED",
                "CANCELLED",
                name="inventory_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "inventory_type",
            sa.Enum(
                "FULL",
                "TARGETED",
                name="inventory_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_by", sa.Uuid(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.Uuid(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validated_by", sa.Uuid(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by", sa.Uuid(), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'CANCELLED' OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT "
            "NULL)",
            name=op.f("ck_inventories_cancelled_has_reason"),
        ),
        sa.CheckConstraint(
            "status <> 'VALIDATED' OR validated_at IS NOT NULL",
            name=op.f("ck_inventories_validated_has_date"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('COUNTING', 'READY_TO_VALIDATE', 'VALIDATED') "
            "OR started_at IS NOT NULL",
            name=op.f("ck_inventories_started_has_date"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('READY_TO_VALIDATE', 'VALIDATED') OR completed_at IS NOT NULL",
            name=op.f("ck_inventories_completed_has_date"),
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by"], ["users.id"], name=op.f("fk_inventories_cancelled_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["completed_by"], ["users.id"], name=op.f("fk_inventories_completed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_inventories_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["started_by"], ["users.id"], name=op.f("fk_inventories_started_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["sites.tenant_id", "sites.id"],
            name=op.f("fk_inventories_tenant_id_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_inventories_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["validated_by"], ["users.id"], name=op.f("fk_inventories_validated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventories")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_inventories_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_inventories_tenant_id_number")),
    )
    op.create_index(op.f("ix_inventories_site_id"), "inventories", ["site_id"], unique=False)
    op.create_index(
        "ix_inventories_tenant_created", "inventories", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_inventories_tenant_id"), "inventories", ["tenant_id"], unique=False)
    op.create_table(
        "inventory_lines",
        sa.Column("inventory_id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("stock_theoretical_initial", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column(
            "stock_theoretical_at_validation", sa.Numeric(precision=18, scale=3), nullable=True
        ),
        sa.Column("quantity_physical", sa.Numeric(precision=18, scale=3), nullable=True),
        sa.Column("quantity_variance", sa.Numeric(precision=18, scale=3), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("adjustment_value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("counted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("counted_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity_physical IS NULL OR counted_at IS NOT NULL",
            name=op.f("ck_inventory_lines_counted_has_date"),
        ),
        sa.CheckConstraint(
            "quantity_physical IS NULL OR quantity_physical >= 0",
            name=op.f("ck_inventory_lines_physical_non_negative"),
        ),
        sa.CheckConstraint(
            "quantity_variance IS NULL OR (stock_theoretical_at_validation IS NOT NULL AND "
            "quantity_physical IS NOT NULL AND quantity_variance = quantity_physical - "
            "stock_theoretical_at_validation)",
            name=op.f("ck_inventory_lines_variance_consistent"),
        ),
        sa.CheckConstraint(
            "stock_theoretical_at_validation IS NULL OR stock_theoretical_at_validation >= 0",
            name=op.f("ck_inventory_lines_at_validation_non_negative"),
        ),
        sa.CheckConstraint(
            "stock_theoretical_initial >= 0", name=op.f("ck_inventory_lines_initial_non_negative")
        ),
        sa.CheckConstraint(
            "unit_cost IS NULL OR unit_cost >= 0",
            name=op.f("ck_inventory_lines_unit_cost_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["counted_by"], ["users.id"], name=op.f("fk_inventory_lines_counted_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "article_id"],
            ["catalog_articles.tenant_id", "catalog_articles.id"],
            name=op.f("fk_inventory_lines_tenant_id_article_id_catalog_articles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "inventory_id"],
            ["inventories.tenant_id", "inventories.id"],
            name=op.f("fk_inventory_lines_tenant_id_inventory_id_inventories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_inventory_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_lines")),
        sa.UniqueConstraint(
            "inventory_id", "article_id", name=op.f("uq_inventory_lines_inventory_id_article_id")
        ),
    )
    op.create_index(
        op.f("ix_inventory_lines_inventory_id"), "inventory_lines", ["inventory_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_lines_tenant_id"), "inventory_lines", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = app_current_tenant_id()) "
            "WITH CHECK (tenant_id = app_current_tenant_id())"
        )
    role = _app_role()
    for privileges, tables in GRANTS.items():
        op.execute(f"GRANT {privileges} ON {', '.join(tables)} TO {role}")


def downgrade() -> None:
    # Mouvements d'ajustement des inventaires. FORCE RLS suspendu le temps de la suppression :
    # le propriétaire agit sur tous les tenants.
    op.execute("ALTER TABLE stock_movements NO FORCE ROW LEVEL SECURITY")
    op.execute("DELETE FROM stock_movements WHERE source_type = 'inventory_count'")
    op.execute("ALTER TABLE stock_movements FORCE ROW LEVEL SECURITY")
    op.execute(f"REVOKE ALL ON {', '.join(TABLES)} FROM {_app_role()}")
    for table in TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_lines_tenant_id"), table_name="inventory_lines")
    op.drop_index(op.f("ix_inventory_lines_inventory_id"), table_name="inventory_lines")
    op.drop_table("inventory_lines")
    op.drop_index(op.f("ix_inventories_tenant_id"), table_name="inventories")
    op.drop_index("ix_inventories_tenant_created", table_name="inventories")
    op.drop_index(op.f("ix_inventories_site_id"), table_name="inventories")
    op.drop_table("inventories")
    # ### end Alembic commands ###
