"""Stock par site (Phase 2.2) : numérotation, niveaux, mouvements, motifs, entrées, sorties.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-24 00:22:15.717001+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.config import get_settings

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_sequences",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_key", sa.String(length=50), nullable=False),
        sa.Column("next_value", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_document_sequences_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "sequence_key", name=op.f("pk_document_sequences")),
    )
    op.create_table(
        "stock_exit_reasons",
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("label", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT is_system OR code IS NOT NULL", name=op.f("ck_stock_exit_reasons_system_has_code")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stock_exit_reasons_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_exit_reasons")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_stock_exit_reasons_tenant_id_code")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_stock_exit_reasons_tenant_id_id")),
    )
    op.create_index(
        op.f("ix_stock_exit_reasons_tenant_id"), "stock_exit_reasons", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_stock_exit_reasons_tenant_label",
        "stock_exit_reasons",
        ["tenant_id", sa.literal_column("lower(label)")],
        unique=True,
    )
    op.create_table(
        "stock_entries",
        sa.Column(
            "kind",
            sa.Enum(
                "PURCHASE",
                "INITIAL_STOCK",
                name="entry_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("document_reference", sa.String(length=100), nullable=True),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "VALIDATED",
                "CANCELLED",
                name="document_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("operation_date", sa.Date(), nullable=False),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validated_by", sa.Uuid(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by", sa.Uuid(), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind <> 'PURCHASE' OR supplier_id IS NOT NULL",
            name=op.f("ck_stock_entries_purchase_has_supplier"),
        ),
        sa.CheckConstraint(
            "status <> 'CANCELLED' OR cancellation_reason IS NOT NULL",
            name=op.f("ck_stock_entries_cancel_has_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by"], ["users.id"], name=op.f("fk_stock_entries_cancelled_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_stock_entries_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["sites.tenant_id", "sites.id"],
            name=op.f("fk_stock_entries_tenant_id_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "supplier_id"],
            ["suppliers.tenant_id", "suppliers.id"],
            name=op.f("fk_stock_entries_tenant_id_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stock_entries_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["validated_by"], ["users.id"], name=op.f("fk_stock_entries_validated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_entries")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_stock_entries_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_stock_entries_tenant_id_number")),
    )
    op.create_index(op.f("ix_stock_entries_site_id"), "stock_entries", ["site_id"], unique=False)
    op.create_index(
        op.f("ix_stock_entries_tenant_id"), "stock_entries", ["tenant_id"], unique=False
    )
    op.create_table(
        "stock_exits",
        sa.Column("reason_id", sa.Uuid(), nullable=False),
        sa.Column("beneficiary", sa.String(length=150), nullable=True),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "VALIDATED",
                "CANCELLED",
                name="document_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("operation_date", sa.Date(), nullable=False),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validated_by", sa.Uuid(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by", sa.Uuid(), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'CANCELLED' OR cancellation_reason IS NOT NULL",
            name=op.f("ck_stock_exits_cancel_has_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by"], ["users.id"], name=op.f("fk_stock_exits_cancelled_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_stock_exits_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "reason_id"],
            ["stock_exit_reasons.tenant_id", "stock_exit_reasons.id"],
            name=op.f("fk_stock_exits_tenant_id_reason_id_stock_exit_reasons"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["sites.tenant_id", "sites.id"],
            name=op.f("fk_stock_exits_tenant_id_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stock_exits_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["validated_by"], ["users.id"], name=op.f("fk_stock_exits_validated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_exits")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_stock_exits_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_stock_exits_tenant_id_number")),
    )
    op.create_index(op.f("ix_stock_exits_site_id"), "stock_exits", ["site_id"], unique=False)
    op.create_index(op.f("ix_stock_exits_tenant_id"), "stock_exits", ["tenant_id"], unique=False)
    op.create_table(
        "stock_entry_lines",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_entry_lines_quantity_positive")),
        sa.CheckConstraint(
            "unit_cost >= 0", name=op.f("ck_stock_entry_lines_unit_cost_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "article_id"],
            ["catalog_articles.tenant_id", "catalog_articles.id"],
            name=op.f("fk_stock_entry_lines_tenant_id_article_id_catalog_articles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "entry_id"],
            ["stock_entries.tenant_id", "stock_entries.id"],
            name=op.f("fk_stock_entry_lines_tenant_id_entry_id_stock_entries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stock_entry_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_entry_lines")),
        sa.UniqueConstraint(
            "entry_id", "article_id", name=op.f("uq_stock_entry_lines_entry_id_article_id")
        ),
    )
    op.create_index(
        op.f("ix_stock_entry_lines_entry_id"), "stock_entry_lines", ["entry_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_entry_lines_tenant_id"), "stock_entry_lines", ["tenant_id"], unique=False
    )
    op.create_table(
        "stock_exit_lines",
        sa.Column("exit_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_exit_lines_quantity_positive")),
        sa.CheckConstraint(
            "unit_cost IS NULL OR unit_cost >= 0",
            name=op.f("ck_stock_exit_lines_unit_cost_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "article_id"],
            ["catalog_articles.tenant_id", "catalog_articles.id"],
            name=op.f("fk_stock_exit_lines_tenant_id_article_id_catalog_articles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "exit_id"],
            ["stock_exits.tenant_id", "stock_exits.id"],
            name=op.f("fk_stock_exit_lines_tenant_id_exit_id_stock_exits"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stock_exit_lines_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_exit_lines")),
        sa.UniqueConstraint(
            "exit_id", "article_id", name=op.f("uq_stock_exit_lines_exit_id_article_id")
        ),
    )
    op.create_index(
        op.f("ix_stock_exit_lines_exit_id"), "stock_exit_lines", ["exit_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_exit_lines_tenant_id"), "stock_exit_lines", ["tenant_id"], unique=False
    )
    op.create_table(
        "stock_levels",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("average_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("min_stock", sa.Numeric(precision=18, scale=3), nullable=True),
        sa.Column("max_stock", sa.Numeric(precision=18, scale=3), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "average_cost >= 0", name=op.f("ck_stock_levels_average_cost_non_negative")
        ),
        sa.CheckConstraint(
            "max_stock IS NULL OR max_stock >= 0",
            name=op.f("ck_stock_levels_max_stock_non_negative"),
        ),
        sa.CheckConstraint(
            "max_stock IS NULL OR min_stock IS NULL OR max_stock >= min_stock",
            name=op.f("ck_stock_levels_max_stock_gte_min"),
        ),
        sa.CheckConstraint(
            "min_stock IS NULL OR min_stock >= 0",
            name=op.f("ck_stock_levels_min_stock_non_negative"),
        ),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_stock_levels_quantity_non_negative")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "article_id"],
            ["catalog_articles.tenant_id", "catalog_articles.id"],
            name=op.f("fk_stock_levels_tenant_id_article_id_catalog_articles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["sites.tenant_id", "sites.id"],
            name=op.f("fk_stock_levels_tenant_id_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stock_levels_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_levels")),
        sa.UniqueConstraint(
            "tenant_id",
            "site_id",
            "article_id",
            name=op.f("uq_stock_levels_tenant_id_site_id_article_id"),
        ),
    )
    op.create_index(
        op.f("ix_stock_levels_article_id"), "stock_levels", ["article_id"], unique=False
    )
    op.create_index(op.f("ix_stock_levels_site_id"), "stock_levels", ["site_id"], unique=False)
    op.create_index(op.f("ix_stock_levels_tenant_id"), "stock_levels", ["tenant_id"], unique=False)
    op.create_table(
        "stock_movements",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column(
            "movement_type",
            sa.Enum(
                "ENTRY",
                "EXIT",
                "CANCELLATION",
                "ADJUSTMENT",
                "TRANSFER_OUT",
                "TRANSFER_IN",
                "SALE",
                name="movement_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("quantity_before", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("quantity_after", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("average_cost_before", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("average_cost_after", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_line_id", sa.Uuid(), nullable=False),
        sa.Column("origin_movement_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity <> 0", name=op.f("ck_stock_movements_quantity_not_zero")),
        sa.CheckConstraint(
            "quantity_after = quantity_before + quantity", name=op.f("ck_stock_movements_balance")
        ),
        sa.CheckConstraint("quantity_after >= 0", name=op.f("ck_stock_movements_never_negative")),
        sa.ForeignKeyConstraint(
            ["origin_movement_id"],
            ["stock_movements.id"],
            name=op.f("fk_stock_movements_origin_movement_id_stock_movements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "article_id"],
            ["catalog_articles.tenant_id", "catalog_articles.id"],
            name=op.f("fk_stock_movements_tenant_id_article_id_catalog_articles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["sites.tenant_id", "sites.id"],
            name=op.f("fk_stock_movements_tenant_id_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_stock_movements_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_stock_movements_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
        sa.UniqueConstraint(
            "tenant_id",
            "source_line_id",
            "movement_type",
            name=op.f("uq_stock_movements_tenant_id_source_line_id_movement_type"),
        ),
    )
    op.create_index(
        op.f("ix_stock_movements_article_id"), "stock_movements", ["article_id"], unique=False
    )
    op.create_index(
        "ix_stock_movements_source", "stock_movements", ["tenant_id", "source_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_tenant_id"), "stock_movements", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_stock_movements_tenant_site_occurred",
        "stock_movements",
        ["tenant_id", "site_id", "occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###
    _enable_rls_and_grants()
    _seed_system_exit_reasons()


def downgrade() -> None:
    _revoke()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_movements_tenant_site_occurred", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_tenant_id"), table_name="stock_movements")
    op.drop_index("ix_stock_movements_source", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_article_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(op.f("ix_stock_levels_tenant_id"), table_name="stock_levels")
    op.drop_index(op.f("ix_stock_levels_site_id"), table_name="stock_levels")
    op.drop_index(op.f("ix_stock_levels_article_id"), table_name="stock_levels")
    op.drop_table("stock_levels")
    op.drop_index(op.f("ix_stock_exit_lines_tenant_id"), table_name="stock_exit_lines")
    op.drop_index(op.f("ix_stock_exit_lines_exit_id"), table_name="stock_exit_lines")
    op.drop_table("stock_exit_lines")
    op.drop_index(op.f("ix_stock_entry_lines_tenant_id"), table_name="stock_entry_lines")
    op.drop_index(op.f("ix_stock_entry_lines_entry_id"), table_name="stock_entry_lines")
    op.drop_table("stock_entry_lines")
    op.drop_index(op.f("ix_stock_exits_tenant_id"), table_name="stock_exits")
    op.drop_index(op.f("ix_stock_exits_site_id"), table_name="stock_exits")
    op.drop_table("stock_exits")
    op.drop_index(op.f("ix_stock_entries_tenant_id"), table_name="stock_entries")
    op.drop_index(op.f("ix_stock_entries_site_id"), table_name="stock_entries")
    op.drop_table("stock_entries")
    op.drop_index("uq_stock_exit_reasons_tenant_label", table_name="stock_exit_reasons")
    op.drop_index(op.f("ix_stock_exit_reasons_tenant_id"), table_name="stock_exit_reasons")
    op.drop_table("stock_exit_reasons")
    op.drop_table("document_sequences")
    # ### end Alembic commands ###


# --- Isolation et droits ----------------------------------------------------------------------

TABLES = (
    "document_sequences",
    "stock_exit_reasons",
    "stock_entries",
    "stock_entry_lines",
    "stock_exits",
    "stock_exit_lines",
    "stock_levels",
    "stock_movements",
)
GRANTS = {
    "SELECT, INSERT, UPDATE": (
        "document_sequences",
        "stock_exit_reasons",
        "stock_entries",
        "stock_exits",
        "stock_levels",
    ),
    # Lignes de brouillon : remplacées tant que le document n'est pas validé.
    "SELECT, INSERT, UPDATE, DELETE": ("stock_entry_lines", "stock_exit_lines"),
    # Journal immuable (STK-07) : ni UPDATE ni DELETE.
    "SELECT, INSERT": ("stock_movements",),
}


def _app_role() -> str:
    return op.get_bind().dialect.identifier_preparer.quote(get_settings().db_app_role)


def _enable_rls_and_grants() -> None:
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = app_current_tenant_id()) "
            "WITH CHECK (tenant_id = app_current_tenant_id())"
        )
    role = _app_role()
    for privileges, tables in GRANTS.items():
        op.execute(f"GRANT {privileges} ON {', '.join(tables)} TO {role}")


def _revoke() -> None:
    op.execute(f"REVOKE ALL ON {', '.join(TABLES)} FROM {_app_role()}")
    for table in TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")


# --- Motifs de sortie système des entreprises existantes (Q7) ---------------------------------
# Copie figée de la liste (une migration ne dépend pas du code applicatif qui évolue).
# La migration s'exécute en propriétaire des tables : le FORCE de la RLS est levé le temps de
# l'insertion, dans cette même transaction ; le rôle applicatif n'est jamais concerné.

SYSTEM_EXIT_REASONS = (
    ("CONSOMMATION_INTERNE", "Consommation interne", "Utilisation par l'entreprise elle-même."),
    ("DOTATION", "Dotation", "Remise à un service, un employé ou un bénéficiaire."),
    ("PERTE", "Perte", "Marchandise perdue ou disparue."),
    ("CASSE", "Casse", "Marchandise endommagée ou détruite."),
    ("ECHANTILLON", "Échantillon", "Échantillon ou article de démonstration."),
    ("AUTRE", "Autre", "Autre motif (à préciser en commentaire)."),
)


def _seed_system_exit_reasons() -> None:
    op.execute("ALTER TABLE tenants NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE stock_exit_reasons NO FORCE ROW LEVEL SECURITY")
    for code, label, description in SYSTEM_EXIT_REASONS:
        op.execute(
            sa.text(
                "INSERT INTO stock_exit_reasons "
                "(id, tenant_id, code, label, description, is_system, is_active) "
                "SELECT gen_random_uuid(), t.id, :code, :label, :description, true, true "
                "FROM tenants t ON CONFLICT DO NOTHING"
            ).bindparams(code=code, label=label, description=description)
        )
    op.execute("ALTER TABLE stock_exit_reasons FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE tenants FORCE ROW LEVEL SECURITY")
