"""Module Clients (Phase 2.3) : table ``customers`` isolée par RLS.

- référence ``CLI-000001`` unique par tenant (séquence de ``document_sequences``) ;
- aucune unicité sur le téléphone ni l'email (plusieurs clients peuvent les partager) ;
- recherche « contient » (caisse / POS) servie par des index trigrammes (extension
  ``pg_trgm``, marquée « trusted » depuis PostgreSQL 13 : le propriétaire de la base peut
  l'installer) ;
- droits du rôle applicatif : ``SELECT, INSERT, UPDATE`` (jamais de suppression physique).

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-24 09:58:24.701342+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.config import get_settings

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _app_role() -> str:
    return op.get_bind().dialect.identifier_preparer.quote(get_settings().db_app_role)


def upgrade() -> None:
    # Conservée au retour arrière : d'autres objets pourront en dépendre.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column(
            "customer_type",
            sa.Enum(
                "INDIVIDUAL",
                "BUSINESS",
                name="customer_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=True),
        sa.Column("tax_id", sa.String(length=50), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("phone2", sa.String(length=30), nullable=True),
        sa.Column("email", sa.String(length=150), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("credit_limit", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "credit_limit IS NULL OR credit_limit >= 0",
            name=op.f("ck_customers_credit_limit_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_customers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_customers_tenant_id_code")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_customers_tenant_id_id")),
    )
    op.create_index(
        "ix_customers_code_trgm",
        "customers",
        ["code"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"code": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_customers_email_trgm",
        "customers",
        ["email"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"email": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_customers_legal_name_trgm",
        "customers",
        ["legal_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"legal_name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_customers_name_trgm",
        "customers",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_customers_phone2_trgm",
        "customers",
        ["phone2"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"phone2": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_customers_phone_trgm",
        "customers",
        ["phone"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"phone": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_customers_tenant_id"), "customers", ["tenant_id"], unique=False)
    # ### end Alembic commands ###

    # Isolation (ADR-0002) et moindre privilège.
    op.execute("ALTER TABLE customers ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE customers FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON customers "
        "USING (tenant_id = app_current_tenant_id()) "
        "WITH CHECK (tenant_id = app_current_tenant_id())"
    )
    op.execute(f"GRANT SELECT, INSERT, UPDATE ON customers TO {_app_role()}")


def downgrade() -> None:
    op.execute(f"REVOKE ALL ON customers FROM {_app_role()}")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON customers")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customers_tenant_id"), table_name="customers")
    op.drop_index(
        "ix_customers_phone_trgm",
        table_name="customers",
        postgresql_using="gin",
        postgresql_ops={"phone": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_customers_phone2_trgm",
        table_name="customers",
        postgresql_using="gin",
        postgresql_ops={"phone2": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_customers_name_trgm",
        table_name="customers",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_customers_legal_name_trgm",
        table_name="customers",
        postgresql_using="gin",
        postgresql_ops={"legal_name": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_customers_email_trgm",
        table_name="customers",
        postgresql_using="gin",
        postgresql_ops={"email": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_customers_code_trgm",
        table_name="customers",
        postgresql_using="gin",
        postgresql_ops={"code": "gin_trgm_ops"},
    )
    op.drop_table("customers")
    # ### end Alembic commands ###
