"""Onboarding persistant (Phase 3.2-B, ADR-0026).

- ``onboarding_steps`` : état de chaque étape d'onboarding d'un tenant (``UNIQUE(tenant_id,
  step_code)``), statuts ``NOT_STARTED`` / ``IN_PROGRESS`` / ``COMPLETED`` ; ``completed_at``
  renseigné si et seulement si l'étape est terminée (``CHECK``) ;
- déclencheur ``onboarding_steps_forward_only`` : le statut ne fait qu'avancer et une étape
  ``COMPLETED`` est définitive (statut, date et auteur de complétion figés) — défense en
  profondeur du contrôle du service ;
- RLS ``ENABLE`` + ``FORCE``, politique ``tenant_isolation`` ; droits du rôle applicatif :
  ``SELECT, INSERT, UPDATE`` (jamais de suppression).

Aucune donnée écrite : les étapes des tenants existants sont créées et évaluées au premier
accès, à partir de leurs données réelles.

Revision ID: 0016
Revises: 0015
Create Date: 2026-09-25
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.config import get_settings

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLE = "onboarding_steps"


def _app_role() -> str:
    return op.get_bind().dialect.identifier_preparer.quote(get_settings().db_app_role)


_RANK = "CASE {s} WHEN 'NOT_STARTED' THEN 0 WHEN 'IN_PROGRESS' THEN 1 WHEN 'COMPLETED' THEN 2 END"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_steps",
        sa.Column("step_code", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                name="onboarding_step_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.Uuid(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'COMPLETED') = (completed_at IS NOT NULL)",
            name=op.f("ck_onboarding_steps_completion_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["completed_by"], ["users.id"], name=op.f("fk_onboarding_steps_completed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_onboarding_steps_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onboarding_steps")),
        sa.UniqueConstraint(
            "tenant_id", "step_code", name=op.f("uq_onboarding_steps_tenant_id_step_code")
        ),
    )
    op.create_index(
        op.f("ix_onboarding_steps_tenant_id"), "onboarding_steps", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    op.execute(
        f"""
        CREATE FUNCTION onboarding_steps_forward_only() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF ({_RANK.format(s="NEW.status")}) < ({_RANK.format(s="OLD.status")})
               OR (OLD.status = 'COMPLETED' AND (
                   NEW.completed_at IS DISTINCT FROM OLD.completed_at
                   OR NEW.completed_by IS DISTINCT FROM OLD.completed_by))
               OR NEW.tenant_id <> OLD.tenant_id
               OR NEW.step_code <> OLD.step_code
            THEN
                RAISE EXCEPTION 'onboarding step % cannot regress', OLD.step_code
                    USING ERRCODE = 'check_violation';
            END IF;
            RETURN NEW;
        END
        $$
        """
    )
    op.execute(
        f"CREATE TRIGGER onboarding_steps_forward_only BEFORE UPDATE ON {TABLE} "
        "FOR EACH ROW EXECUTE FUNCTION onboarding_steps_forward_only()"
    )
    op.execute(f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {TABLE} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON {TABLE} "
        "USING (tenant_id = app_current_tenant_id()) "
        "WITH CHECK (tenant_id = app_current_tenant_id())"
    )
    op.execute(f"GRANT SELECT, INSERT, UPDATE ON {TABLE} TO {_app_role()}")


def downgrade() -> None:
    op.execute(f"REVOKE ALL ON {TABLE} FROM {_app_role()}")
    op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {TABLE}")
    op.execute(f"DROP TRIGGER IF EXISTS onboarding_steps_forward_only ON {TABLE}")
    op.execute("DROP FUNCTION IF EXISTS onboarding_steps_forward_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_onboarding_steps_tenant_id"), table_name="onboarding_steps")
    op.drop_table("onboarding_steps")
    # ### end Alembic commands ###
