"""Paiements des ventes (Phase 2.7, ADR-0020).

- ``payments`` : encaissements d'une vente validée ; numéro ``PAY-000001`` unique par tenant ;
  montant > 0 ; moyen et statut en texte contraint ; clé d'idempotence unique par tenant ;
  FK composite ``(tenant_id, sale_id, site_id)`` → ``sales`` : même tenant ET même site que
  la vente (nouvelle contrainte d'unicité ``(tenant_id, id, site_id)`` sur ``sales``) ;
- RLS ``ENABLE`` + ``FORCE``, politique ``tenant_isolation`` ; droits du rôle applicatif :
  ``SELECT, INSERT, UPDATE`` (un paiement n'est jamais supprimé : annulation).

Aucun état de paiement stocké sur ``sales`` : payé / reste / état sont calculés.

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-24
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.config import get_settings

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _app_role() -> str:
    return op.get_bind().dialect.identifier_preparer.quote(get_settings().db_app_role)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Cible de la FK composite (tenant, vente, site) : créée AVANT la table des paiements.
    op.create_unique_constraint(
        op.f("uq_sales_tenant_id_id_site_id"), "sales", ["tenant_id", "id", "site_id"]
    )
    op.create_table(
        "payments",
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("sale_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "CASH",
                "MOBILE_MONEY",
                "CARD",
                "BANK_TRANSFER",
                "OTHER",
                name="payment_method",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "CANCELLED",
                name="payment_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by", sa.Uuid(), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'CANCELLED' OR (cancelled_at IS NOT NULL "
            "AND cancellation_reason IS NOT NULL)",
            name=op.f("ck_payments_cancelled_has_reason"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["cancelled_by"], ["users.id"], name=op.f("fk_payments_cancelled_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_payments_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sale_id", "site_id"],
            ["sales.tenant_id", "sales.id", "sales.site_id"],
            name=op.f("fk_payments_tenant_id_sale_id_site_id_sales"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["sites.tenant_id", "sites.id"],
            name=op.f("fk_payments_tenant_id_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_payments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_payments_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name=op.f("uq_payments_tenant_id_idempotency_key")
        ),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_payments_tenant_id_number")),
    )
    op.create_index(op.f("ix_payments_site_id"), "payments", ["site_id"], unique=False)
    op.create_index(op.f("ix_payments_tenant_id"), "payments", ["tenant_id"], unique=False)
    op.create_index(
        "ix_payments_tenant_paid_at", "payments", ["tenant_id", "paid_at"], unique=False
    )
    op.create_index("ix_payments_tenant_sale", "payments", ["tenant_id", "sale_id"], unique=False)
    # ### end Alembic commands ###

    op.execute("ALTER TABLE payments ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE payments FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON payments "
        "USING (tenant_id = app_current_tenant_id()) "
        "WITH CHECK (tenant_id = app_current_tenant_id())"
    )
    op.execute(f"GRANT SELECT, INSERT, UPDATE ON payments TO {_app_role()}")


def downgrade() -> None:
    op.execute(f"REVOKE ALL ON payments FROM {_app_role()}")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON payments")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payments_tenant_sale", table_name="payments")
    op.drop_index("ix_payments_tenant_paid_at", table_name="payments")
    op.drop_index(op.f("ix_payments_tenant_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_site_id"), table_name="payments")
    op.drop_table("payments")
    # Après la table des paiements (sa FK composite en dépend).
    op.drop_constraint(op.f("uq_sales_tenant_id_id_site_id"), "sales", type_="unique")
    # ### end Alembic commands ###
