"""Socle plateforme : identité, tenants, sites, accès, catalogue, abonnements, audit + RLS.

Revision ID: 0001
Revises:
Create Date: 2026-09-23 22:05:06.636619+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.config import get_settings

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_profiles",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("navigation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("terminology", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_business_profiles")),
    )
    op.create_table(
        "plans",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("grace_days", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_plans")),
    )
    op.create_table(
        "subscription_access_policies",
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("allowed_access", sa.ARRAY(sa.String(length=16)), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("status", name=op.f("pk_subscription_access_policies")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("previous_token_hash", sa.String(length=64), nullable=True),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
    )
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "business_profile_modules",
        sa.Column("profile_code", sa.String(length=50), nullable=False),
        sa.Column("module_code", sa.String(length=64), nullable=False),
        sa.Column("default_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_code"],
            ["business_profiles.code"],
            name=op.f("fk_business_profile_modules_profile_code_business_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "profile_code", "module_code", name=op.f("pk_business_profile_modules")
        ),
    )
    op.create_table(
        "plan_modules",
        sa.Column("plan_code", sa.String(length=50), nullable=False),
        sa.Column("module_code", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_code"],
            ["plans.code"],
            name=op.f("fk_plan_modules_plan_code_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("plan_code", "module_code", name=op.f("pk_plan_modules")),
    )
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "suspended",
                name="tenant_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("business_profile_code", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_profile_code"],
            ["business_profiles.code"],
            name=op.f("fk_tenants_business_profile_code_business_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("site_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_audit_logs_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        "ix_audit_logs_tenant_occurred", "audit_logs", ["tenant_id", "occurred_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("template_code", sa.String(length=50), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_roles_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_roles_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_roles_tenant_id_name")),
    )
    op.create_index(op.f("ix_roles_tenant_id"), "roles", ["tenant_id"], unique=False)
    op.create_table(
        "sites",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "store",
                "warehouse",
                "restaurant",
                "other",
                name="site_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_sites_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sites")),
        sa.UniqueConstraint("tenant_id", "code", name=op.f("uq_sites_tenant_id_code")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_sites_tenant_id_id")),
    )
    op.create_index(op.f("ix_sites_tenant_id"), "sites", ["tenant_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("plan_code", sa.String(length=50), nullable=False),
        sa.Column(
            "billing_period",
            sa.Enum(
                "monthly",
                "annual",
                name="billing_period",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "trial",
                "active",
                "past_due",
                "expired",
                "suspended",
                "cancelled",
                name="subscription_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_code"],
            ["plans.code"],
            name=op.f("fk_subscriptions_plan_code_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_subscriptions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("tenant_id", name=op.f("uq_subscriptions_tenant_id")),
    )
    op.create_index(
        op.f("ix_subscriptions_tenant_id"), "subscriptions", ["tenant_id"], unique=False
    )
    op.create_table(
        "tenant_memberships",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "suspended",
                name="membership_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column("all_sites", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_memberships_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tenant_memberships_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_memberships")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_tenant_memberships_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "user_id", name=op.f("uq_tenant_memberships_tenant_id_user_id")
        ),
    )
    op.create_index(
        op.f("ix_tenant_memberships_tenant_id"), "tenant_memberships", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_tenant_memberships_user_id"), "tenant_memberships", ["user_id"], unique=False
    )
    op.create_table(
        "tenant_modules",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("module_code", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_modules_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "module_code", name=op.f("pk_tenant_modules")),
    )
    op.create_table(
        "membership_roles",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["tenant_memberships.tenant_id", "tenant_memberships.id"],
            name=op.f("fk_membership_roles_tenant_id_membership_id_tenant_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "role_id"],
            ["roles.tenant_id", "roles.id"],
            name=op.f("fk_membership_roles_tenant_id_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["sites.tenant_id", "sites.id"],
            name=op.f("fk_membership_roles_tenant_id_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_membership_roles_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_roles")),
        sa.UniqueConstraint(
            "membership_id",
            "role_id",
            "site_id",
            name=op.f("uq_membership_roles_membership_id_role_id_site_id"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_membership_roles_membership_id"),
        "membership_roles",
        ["membership_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_membership_roles_tenant_id"), "membership_roles", ["tenant_id"], unique=False
    )
    op.create_table(
        "membership_sites",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "membership_id"],
            ["tenant_memberships.tenant_id", "tenant_memberships.id"],
            name=op.f("fk_membership_sites_tenant_id_membership_id_tenant_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["sites.tenant_id", "sites.id"],
            name=op.f("fk_membership_sites_tenant_id_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_membership_sites_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("membership_id", "site_id", name=op.f("pk_membership_sites")),
    )
    op.create_index(
        op.f("ix_membership_sites_tenant_id"), "membership_sites", ["tenant_id"], unique=False
    )
    op.create_table(
        "role_permissions",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_code", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "role_id"],
            ["roles.tenant_id", "roles.id"],
            name=op.f("fk_role_permissions_tenant_id_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_role_permissions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_code", name=op.f("pk_role_permissions")),
    )
    op.create_index(
        op.f("ix_role_permissions_tenant_id"), "role_permissions", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###
    _create_rls()
    _grant_app_role()


def downgrade() -> None:
    _revoke_app_role()
    _drop_rls()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_role_permissions_tenant_id"), table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_membership_sites_tenant_id"), table_name="membership_sites")
    op.drop_table("membership_sites")
    op.drop_index(op.f("ix_membership_roles_tenant_id"), table_name="membership_roles")
    op.drop_index(op.f("ix_membership_roles_membership_id"), table_name="membership_roles")
    op.drop_table("membership_roles")
    op.drop_table("tenant_modules")
    op.drop_index(op.f("ix_tenant_memberships_user_id"), table_name="tenant_memberships")
    op.drop_index(op.f("ix_tenant_memberships_tenant_id"), table_name="tenant_memberships")
    op.drop_table("tenant_memberships")
    op.drop_index(op.f("ix_subscriptions_tenant_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_sites_tenant_id"), table_name="sites")
    op.drop_table("sites")
    op.drop_index(op.f("ix_roles_tenant_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_tenant_occurred", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("tenants")
    op.drop_table("plan_modules")
    op.drop_table("business_profile_modules")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_table("users")
    op.drop_table("subscription_access_policies")
    op.drop_table("plans")
    op.drop_table("business_profiles")
    # ### end Alembic commands ###


# --- Row-Level Security ---------------------------------------------------------------------
# Contexte fixé par l'application à chaque transaction (voir app/core/db.py) :
#   app.tenant_id : tenant actif ; app.user_id : utilisateur authentifié.
# Sans contexte, aucune ligne tenant-scoped n'est visible ni insérable.

TENANT_SCOPED_TABLES = (
    "sites",
    "tenant_modules",
    "tenant_memberships",
    "membership_sites",
    "membership_roles",
    "roles",
    "role_permissions",
    "subscriptions",
)


def _create_rls() -> None:
    op.execute(
        """
        CREATE FUNCTION app_current_tenant_id() RETURNS uuid
            LANGUAGE sql STABLE
            AS $$ SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid $$;
        CREATE FUNCTION app_current_user_id() RETURNS uuid
            LANGUAGE sql STABLE
            AS $$ SELECT NULLIF(current_setting('app.user_id', true), '')::uuid $$;
        """
    )
    for table in TENANT_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (tenant_id = app_current_tenant_id()) "
            "WITH CHECK (tenant_id = app_current_tenant_id())"
        )

    # Sans tenant actif uniquement : un utilisateur authentifié peut lister ses propres
    # appartenances (choix du tenant). Dès qu'un tenant est actif, seule l'isolation
    # stricte s'applique (les politiques permissives se cumulent par OU).
    op.execute(
        "CREATE POLICY own_memberships_read ON tenant_memberships FOR SELECT "
        "USING (app_current_tenant_id() IS NULL AND user_id = app_current_user_id())"
    )

    op.execute("ALTER TABLE tenants ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE tenants FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON tenants "
        "USING (id = app_current_tenant_id()) WITH CHECK (id = app_current_tenant_id())"
    )
    # ... et lire les tenants dont il est membre (même restriction).
    op.execute(
        "CREATE POLICY member_tenants_read ON tenants FOR SELECT "
        "USING (app_current_tenant_id() IS NULL AND id IN ("
        "SELECT m.tenant_id FROM tenant_memberships m WHERE m.user_id = app_current_user_id()))"
    )

    # Journal d'audit : lecture limitée au tenant actif ; insertion pour le tenant actif ou
    # pour un évènement hors tenant (tenant_id nul, ex. échec de connexion).
    op.execute("ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE audit_logs FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_read ON audit_logs FOR SELECT "
        "USING (tenant_id = app_current_tenant_id())"
    )
    op.execute(
        "CREATE POLICY tenant_insert ON audit_logs FOR INSERT "
        "WITH CHECK (tenant_id IS NULL OR tenant_id = app_current_tenant_id())"
    )


def _drop_rls() -> None:
    for table in (*TENANT_SCOPED_TABLES, "tenants"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    op.execute("DROP POLICY IF EXISTS own_memberships_read ON tenant_memberships")
    op.execute("DROP POLICY IF EXISTS member_tenants_read ON tenants")
    op.execute("DROP POLICY IF EXISTS tenant_read ON audit_logs")
    op.execute("DROP POLICY IF EXISTS tenant_insert ON audit_logs")
    op.execute("DROP FUNCTION IF EXISTS app_current_tenant_id()")
    op.execute("DROP FUNCTION IF EXISTS app_current_user_id()")


# --- Droits du rôle applicatif (principe du moindre privilège) -------------------------------
# Le rôle doit exister (créé par l'exploitation : docker/postgres/init/, CI). Il n'est ni
# propriétaire des tables ni BYPASSRLS.

GRANTS = {
    # Catalogue : lecture seule (synchronisé par le rôle propriétaire).
    "SELECT": (
        "business_profiles",
        "business_profile_modules",
        "plans",
        "plan_modules",
        "subscription_access_policies",
    ),
    "SELECT, INSERT, UPDATE": (
        "users",
        "tenants",
        "sites",
        "tenant_modules",
        "tenant_memberships",
        "subscriptions",
    ),
    "SELECT, INSERT, UPDATE, DELETE": (
        "auth_sessions",
        "roles",
        "role_permissions",
        "membership_sites",
        "membership_roles",
    ),
    # Audit : append-only.
    "SELECT, INSERT": ("audit_logs",),
}


def _app_role() -> str:
    role = get_settings().db_app_role
    return op.get_bind().dialect.identifier_preparer.quote(role)


def _grant_app_role() -> None:
    role = _app_role()
    op.execute(f"GRANT USAGE ON SCHEMA public TO {role}")
    for privileges, tables in GRANTS.items():
        op.execute(f"GRANT {privileges} ON {', '.join(tables)} TO {role}")
    op.execute(
        f"GRANT EXECUTE ON FUNCTION app_current_tenant_id(), app_current_user_id() TO {role}"
    )


def _revoke_app_role() -> None:
    role = _app_role()
    tables = sorted({t for group in GRANTS.values() for t in group})
    op.execute(f"REVOKE ALL ON {', '.join(tables)} FROM {role}")
