"""Licences des sites (Phase 3.3-B2, ADR-0034).

- ``licenses`` : licence d'un site, générée par TechNova depuis un paiement **confirmé**,
  signée (Ed25519) par le Signing Service — la clé privée n'est jamais ici. Clés étrangères
  composites : abonnement du même tenant ET du même site ``(tenant_id, site_id,
  subscription_id)``, paiement de cet abonnement ``(tenant_id, subscription_id, payment_id)``,
  licence remplacée du même tenant. Une seule licence non révoquée par paiement ; une licence
  n'est remplacée qu'une fois ; numéro global ``LIC-AAAA-NNNNN`` (séquence
  ``license_number_seq``).
- Immutabilité : déclencheur ``licenses_final`` — rien ne change après l'émission, sauf la
  révocation ``ISSUED`` → ``REVOKED`` (définitive, jamais restaurée).
- RLS ``ENABLE`` + ``FORCE``. Rôle applicatif : ``tenant_isolation``, ``SELECT`` seulement
  (l'entreprise lit ses licences, ne les crée ni ne les modifie jamais). Rôle de la console :
  lecture, émission (``INSERT`` d'une licence ``ISSUED``) et révocation (``UPDATE`` des seules
  colonnes de révocation d'une licence ``ISSUED``) ; jamais de suppression.

Revision ID: 0021
Revises: 0020
Create Date: 2026-09-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.config import get_settings

revision: str = "0021"
down_revision: str | None = "0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLE = "licenses"
SEQUENCE = "license_number_seq"
REVOCATION_COLUMNS = ("status", "revoked_at", "revoked_by", "revocation_reason", "updated_at")


def _roles() -> tuple[str, str]:
    settings = get_settings()
    quote = op.get_bind().dialect.identifier_preparer.quote
    return quote(settings.db_app_role), quote(settings.db_platform_role)


def upgrade() -> None:
    # Cibles des clés étrangères composites des licences.
    op.create_unique_constraint(
        op.f("uq_subscription_payments_tenant_id_subscription_id_id"),
        "subscription_payments",
        ["tenant_id", "subscription_id", "id"],
    )
    op.create_unique_constraint(
        op.f("uq_subscriptions_tenant_id_site_id_id"),
        "subscriptions",
        ["tenant_id", "site_id", "id"],
    )
    op.execute(f"CREATE SEQUENCE {SEQUENCE} AS bigint START 1")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "licenses",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("license_number", sa.String(length=20), nullable=False),
        sa.Column("license_version", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("plan_code", sa.String(length=50), nullable=False),
        sa.Column(
            "billing_period",
            sa.Enum(
                "monthly",
                "annual",
                name="billing_period",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_activations", sa.Integer(), nullable=False),
        sa.Column("modules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limits", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("issued_by", sa.Uuid(), nullable=True),
        sa.Column("key_id", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("signature", sa.Text(), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ISSUED",
                "REVOKED",
                name="license_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.Uuid(), nullable=True),
        sa.Column("revocation_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'REVOKED') = (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)",
            name=op.f("ck_licenses_revocation_consistent"),
        ),
        sa.CheckConstraint(
            "license_number ~ '^LIC-[0-9]{4}-[0-9]{5,}$'", name=op.f("ck_licenses_number_format")
        ),
        sa.CheckConstraint(
            "(supersedes_id IS NULL) = (license_version = 1)",
            name=op.f("ck_licenses_supersedes_consistent"),
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_licenses_instants_ordered")),
        sa.CheckConstraint("license_version >= 1", name=op.f("ck_licenses_version_positive")),
        sa.CheckConstraint(
            "max_activations BETWEEN 1 AND 10000", name=op.f("ck_licenses_max_activations_range")
        ),
        sa.CheckConstraint(
            "revocation_reason IS NULL OR length(btrim(revocation_reason)) > 0",
            name=op.f("ck_licenses_revocation_reason_present"),
        ),
        sa.CheckConstraint("valid_until >= valid_from", name=op.f("ck_licenses_period_ordered")),
        sa.ForeignKeyConstraint(
            ["issued_by"],
            ["users.id"],
            name=op.f("fk_licenses_issued_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plan_code"],
            ["plans.code"],
            name=op.f("fk_licenses_plan_code_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by"],
            ["users.id"],
            name=op.f("fk_licenses_revoked_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "subscription_id"],
            ["subscriptions.tenant_id", "subscriptions.site_id", "subscriptions.id"],
            name=op.f("fk_licenses_tenant_id_site_id_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "subscription_id", "payment_id"],
            [
                "subscription_payments.tenant_id",
                "subscription_payments.subscription_id",
                "subscription_payments.id",
            ],
            name=op.f("fk_licenses_tenant_id_subscription_id_payment_id_subscription_payments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "supersedes_id"],
            ["licenses.tenant_id", "licenses.id"],
            name=op.f("fk_licenses_tenant_id_supersedes_id_licenses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_licenses_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_licenses")),
        sa.UniqueConstraint("license_number", name=op.f("uq_licenses_license_number")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_licenses_tenant_id_id")),
    )
    op.create_index(
        "ix_licenses_status_created", "licenses", ["status", "created_at"], unique=False
    )
    op.create_index(
        "ix_licenses_subscription_period",
        "licenses",
        ["tenant_id", "subscription_id", "starts_at"],
        unique=False,
    )
    op.create_index(op.f("ix_licenses_tenant_id"), "licenses", ["tenant_id"], unique=False)
    op.create_index(
        "uq_licenses_issued_payment",
        "licenses",
        ["tenant_id", "payment_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ISSUED'"),
    )
    op.create_index(
        "uq_licenses_supersedes",
        "licenses",
        ["tenant_id", "supersedes_id"],
        unique=True,
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE FUNCTION licenses_final() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.status <> 'ISSUED'
               OR NEW.status <> 'REVOKED'
               OR (to_jsonb(NEW) - ARRAY['status', 'revoked_at', 'revoked_by',
                                         'revocation_reason', 'updated_at'])
                  IS DISTINCT FROM
                  (to_jsonb(OLD) - ARRAY['status', 'revoked_at', 'revoked_by',
                                         'revocation_reason', 'updated_at'])
            THEN
                RAISE EXCEPTION 'license % is immutable (only ISSUED -> REVOKED)', OLD.id
                    USING ERRCODE = 'check_violation';
            END IF;
            RETURN NEW;
        END
        $$
        """
    )
    op.execute(
        f"CREATE TRIGGER licenses_final BEFORE UPDATE ON {TABLE} "
        "FOR EACH ROW EXECUTE FUNCTION licenses_final()"
    )

    app_role, platform_role = _roles()
    op.execute(f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {TABLE} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON {TABLE} TO {app_role} "
        "USING (tenant_id = app_current_tenant_id()) "
        "WITH CHECK (tenant_id = app_current_tenant_id())"
    )
    op.execute(f"GRANT SELECT ON {TABLE} TO {app_role}")

    op.execute(f"CREATE POLICY platform_read ON {TABLE} FOR SELECT TO {platform_role} USING (true)")
    op.execute(
        f"CREATE POLICY platform_issue ON {TABLE} FOR INSERT TO {platform_role} "
        "WITH CHECK (status = 'ISSUED')"
    )
    op.execute(
        f"CREATE POLICY platform_revoke ON {TABLE} FOR UPDATE TO {platform_role} "
        "USING (status = 'ISSUED') WITH CHECK (status = 'REVOKED')"
    )
    op.execute(f"GRANT SELECT, INSERT ON {TABLE} TO {platform_role}")
    op.execute(f"GRANT UPDATE ({', '.join(REVOCATION_COLUMNS)}) ON {TABLE} TO {platform_role}")
    op.execute(f"GRANT USAGE ON SEQUENCE {SEQUENCE} TO {platform_role}")


def downgrade() -> None:
    app_role, platform_role = _roles()
    op.execute(f"REVOKE ALL ON {TABLE} FROM {app_role}")
    op.execute(f"REVOKE ALL ON {TABLE} FROM {platform_role}")
    op.execute(f"REVOKE ALL ON SEQUENCE {SEQUENCE} FROM {platform_role}")
    for policy in ("platform_revoke", "platform_issue", "platform_read", "tenant_isolation"):
        op.execute(f"DROP POLICY IF EXISTS {policy} ON {TABLE}")
    op.execute(f"DROP TRIGGER IF EXISTS licenses_final ON {TABLE}")
    op.execute("DROP FUNCTION IF EXISTS licenses_final()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_licenses_supersedes",
        table_name="licenses",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_licenses_issued_payment",
        table_name="licenses",
        postgresql_where=sa.text("status = 'ISSUED'"),
    )
    op.drop_index(op.f("ix_licenses_tenant_id"), table_name="licenses")
    op.drop_index("ix_licenses_subscription_period", table_name="licenses")
    op.drop_index("ix_licenses_status_created", table_name="licenses")
    op.drop_table("licenses")
    op.execute(f"DROP SEQUENCE IF EXISTS {SEQUENCE}")
    op.drop_constraint(
        op.f("uq_subscriptions_tenant_id_site_id_id"), "subscriptions", type_="unique"
    )
    op.drop_constraint(
        op.f("uq_subscription_payments_tenant_id_subscription_id_id"),
        "subscription_payments",
        type_="unique",
    )
    # ### end Alembic commands ###
